Update Start/Stop Documentation
FusionAuth/fusionauth-site pull request #1590
Opened 2022-09-09 12:59 UTC by spwitt

FusionAuth removed Tomcat in version 1.37.0. This change updates instructions for starting and stopping FusionAuth and Elasticsearch while maintaining the instructions for earlier versions.

- https://github.com/FusionAuth/fusionauth-issues/issues/1848

2022-09-09 13:01 UTC, spwitt commented on site/docs/v1/tech/5-minute-setup-guide.adoc
> +If you are on Windows, you'll need to use the `startup.ps1` file instead.
If we decide to keep two versions of the page, do we need to create a copy of this one?

2022-09-09 13:04 UTC, spwitt commented on site/docs/v1/tech/tutorials/start-and-stop.adoc
> +/usr/local/fusionauth/fusionauth-app/bin/start.sh
Should this page mention `startup` and `shutdown` scripts that start/stop Elastic and FusionAuth in one step?

2022-09-09 14:31 UTC, robotdan reviewed
added a few comments, comments on copy will apply to both install guides.

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/5-minute-setup-guide.adoc
> +If you are on Windows, you'll need to use the `startup.ps1` file instead.
We'll need to mention the version here and when to use `startup.bat` vs `startp.ps1`.

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/admin-guide/upgrade-pre-1-37.adoc
> +---
Is this just a straight copy? i.e. I don't need to review it- this isn't new content?

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/admin-guide/upgrade-pre-1-37.adoc
> +      |-- 1.36.0.sql
We are missing a file here, we need to add `1.37.0`.

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/shared/_post-1-37-note.adoc
> +The method to start FusionAuth underwent changes in version 1.37.
The commands to start FusionAuth changed in version `1.37.0`.

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/shared/_post-1-37-note.adoc
> +If you are looking for the documentation for 1.36 and below, link:{137_link}[look here].
`1.36.0` - there is no such version as `1.36`

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/shared/_pre-1-37-warning.adoc
> +The method to start FusionAuth underwent changes in version 1.37. The below only applies to versions 1.36 and earlier.
The commands to start FusionAuth changed in version `1.37.0`. The following instructions apply to versions up to `1.36.0`.

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/shared/_pre-1-37-warning.adoc
> +If you are looking for the documentation for 1.37 and higher, link:{137_link}[look here].
> ... for versions `1.37.0` and higher, ...

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/tutorials/start-and-stop-pre-1-37.adoc
> +If you are using the FusionAuth server version, may need to manually start or stop FusionAuth periodically. If you find yourself in this situation you'll be glad you know how.
Is this the copy we use other places? `server version` may be confusing. Should we say 

> If you are self-hosting FusionAuth, you may need...

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/tutorials/start-and-stop-pre-1-37.adoc
> +Unless you are hosting and managing FusionAuth these instructions do not apply to you. FusionAuth manages and monitors instances hosted in our private
> Unless you are self-hosting FusionAuth

2022-09-09 14:31 UTC, robotdan commented on site/docs/v1/tech/tutorials/start-and-stop-pre-1-37.adoc
> +*Note* that you *MUST* start the FusionAuth Search before starting the FusionAuth App service. You should also shutdown the Search Engine last. FusionAuth
This isn't that strong of a requirement any longer since we will wait. We do recommend you start search first.

2022-09-09 15:05 UTC, mooreds requested changes

2022-09-09 15:05 UTC, mooreds commented on site/docs/v1/tech/tutorials/start-and-stop.adoc
> +/usr/local/fusionauth/fusionauth-app/bin/start.sh
Do we now drive ES from the same script? How does that work if the user is using the database search engine? Do they manually have to edit the startup scripts?

2022-09-09 15:05 UTC, mooreds commented on site/docs/v1/tech/tutorials/start-and-stop.adoc
> +.Start FusionAuth
Doh! Good catch.

2022-09-12 13:40 UTC, spwitt commented on site/docs/v1/tech/5-minute-setup-guide.adoc
> +If you are on Windows, you'll need to use the `startup.ps1` file instead.
I think that Windows should make a comeback in 1.40, unless we have rules on versioning. It's much easier to say Windows was unavailable in versions 1.37-1.39 than saying you need to be running 1.39.2  or something.

2022-09-12 13:41 UTC, spwitt commented on site/docs/v1/tech/installation-guide/fusionauth-app.adoc
>  [source]
Yes. The `exe` that installs the service has moved, but the commands to start/stop are the same. This document did not include instructions on how to install the Windows service.

2022-09-12 13:47 UTC, spwitt commented on site/docs/v1/tech/installation-guide/fast-path.adoc
> +[source,title=Shutdown FusionAuth]
Windows didn't have a separate `shutdown.ps1` script before.

2022-09-12 20:45 UTC, spwitt commented
I tried to rebase and messed everything up. Please use the new request instead
- https://github.com/FusionAuth/fusionauth-site/pull/1596

2022-09-12 20:45 UTC, closed without merging