Start Forgot Password without Email Template
FusionAuth/fusionauth-site pull request #1773
Opened 2022-12-08 18:51 UTC by spwitt

Add a note to User API doc about starting the forgot password workflow without a configured email template if not requesting FusionAuth to send the email.

Related:
- https://github.com/FusionAuth/fusionauth-issues/issues/1735

Requires internal:
- https://github.com/FusionAuth/fusionauth-app/pull/160

2023-02-17 18:27 UTC, mooreds requested changes

2023-02-17 18:27 UTC, mooreds commented on site/docs/v1/tech/apis/users.adoc
> +false will skip the email attempt and only set the `changePasswordId` for the user. This also allows you to start the forgot password flow without a Forgot Password Email Template.
```suggestion
false will skip the email attempt and only set the `changePasswordId` for the user and allow you to start the forgot password flow without a Forgot Password Email Template.
```

2023-02-17 18:34 UTC, mooreds approved these changes

2023-02-17 18:40 UTC, merged

2023-02-22 17:09 UTC, robotdan commented
Added since tag and some additional clarification.
https://github.com/FusionAuth/fusionauth-site/commit/da7ef64802021b3287f4af3a8b0fb0c84c9a4bf5