Email template search API documentation
FusionAuth/fusionauth-site pull request #1920
Opened 2023-02-07 23:33 UTC by mmanes

Add doc for `/api/email/template/search`

## Related PRs
- https://github.com/FusionAuth/fusionauth-app/pull/197
- https://github.com/FusionAuth/fusionauth-client-builder/pull/57

2023-02-09 23:50 UTC, mooreds requested changes
Small change desired.

2023-02-09 23:50 UTC, mooreds commented on site/docs/v1/tech/apis/emails.adoc
good catch

2023-02-09 23:50 UTC, mooreds commented on site/docs/src/json/email-templates/search-response.json
> +      "name": "Hello World",
These keys should be in alphabetical order.

2023-04-17 18:25 UTC, robotdan approved these changes

2023-04-17 18:25 UTC, merged