Add Preferred languages to Application Registration Configuration
FusionAuth/fusionauth-site pull request #1949
Opened 2023-02-17 15:12 UTC by spwitt

Add `preferredLanguages` to `ApplicationRegistrationConfiguration` APIs. Update screenshot.

**Site Issue**:
- https://github.com/FusionAuth/fusionauth-site/issues/1943

**Related Issue**:
- https://github.com/FusionAuth/fusionauth-issues/issues/1738

2023-02-24 22:22 UTC, mooreds requested changes
Can you please update this tutorial with a new screenshot? https://fusionauth.io/docs/v1/tech/guides/basic-registration-forms

Not sure if this should be documented here, but what does the preferred languages field look like? is it the same as the locale selector? How do I control what shows up there?

2023-03-13 16:21 UTC, spwitt commented
@mooreds updated the guide screenshot.

The selection uses https://fusionauth.io/docs/v1/tech/reference/data-types#locales

There is no way to configure which locales appear in the list similar to the existing preferred languages dropdown.

2023-03-13 16:38 UTC, mooreds approved these changes
One small change requested.

2023-03-13 16:38 UTC, mooreds commented on site/docs/v1/tech/apis/_application-request-body.adoc
> +Determines if the `preferredLanguages` field will be included on the registration form.
```suggestion
Determines if the `preferredLanguages` field will be included on the registration form. The field will display all available link:/docs/v1/tech/reference/data-types#locales[locales] and is not configurable.
```

2023-04-03 18:09 UTC, mooreds commented
Or is this waiting for 1.45? Oops, looks like it is.

2023-06-30 20:34 UTC, mooreds commented
Would be awesome if this made it into 1.47.

2023-07-27 21:58 UTC, robotdan approved these changes

2023-07-27 21:58 UTC, robotdan commented on site/docs/v1/tech/apis/_application-request-body.adoc
> +[field]#application.registrationConfiguration.preferredLanguages.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.44.0#::
1.47.0, same for other places as well.

2023-07-27 21:58 UTC, robotdan commented on site/docs/v1/tech/apis/_application-request-body.adoc
> +Determines if the `preferredLanguages` field will be included on the registration form. The field will display all available link:/docs/v1/tech/reference/data-types#locales[locales] and is not config
None of the basic form values are really configurable? 

> and is not configurable.

Does this just mean you don't get to choose the values displayed? If so, this is not really accurate. You could build your own locale selector. Our default control uses `fusionAuth.locales()` in a `[#list` to iterate through all of the values, but you don't have to use this.

2023-07-28 13:12 UTC, merged

2023-07-28 13:44 UTC, mooreds commented
@spwitt super exciting! This is great for folks who are on the community version and want to make sure their initial emails are sent out in the correct language.