Update rules for capitalizing domain objects.
FusionAuth/fusionauth-site pull request #2027
Opened 2023-03-11 17:48 UTC by jaywood128

2023-03-12 21:21 UTC, robotdan approved these changes

2023-03-12 22:10 UTC, mooreds requested changes
Please add a note on the welcome page explaining the convention (can be similar text thw ath you have in the examples). https://github.com/FusionAuth/fusionauth-site/blob/master/site/docs/v1/tech/index.adoc

2023-03-13 19:26 UTC, jaywood128 commented
> https://github.com/FusionAuth/fusionauth-site/blob/master/site/docs/v1/tech/index.adoc

The index page is customer-facing so why would be include our internal style guidelines there? Is this if someone wanted to open a PR against fusionauth-site? @mooreds

2023-03-13 19:35 UTC, mooreds commented
So our customers know what our convention is. They're the ones reading it, after all :) @jaywood128

2023-03-13 20:13 UTC, mooreds requested changes
Modified to reflect that this is guidance for a user reading, not a contributor.

2023-03-13 20:13 UTC, mooreds commented on site/docs/v1/tech/index.adoc
> +* *Documentation Style Guidelines*: Here are some guidelines to follow when contributing documentation.
```suggestion

== Documentation Conventions

```

2023-03-13 20:13 UTC, mooreds commented on site/docs/v1/tech/index.adoc
> +- Capitalize all domain objects, especially when calling the API in which the object is created and/or updated in FusionAuth.
```suggestion
- We apitalize all domain objects, especially when calling the API in which the object is created and/or updated in FusionAuth.
```

2023-03-13 20:13 UTC, mooreds commented on site/docs/v1/tech/index.adoc
> +- If referring to something that exists as a domain object in FusionAuth, but you are not explicitly referring to an object being created/updated in FusionAuth, use lowercase.
```suggestion
- If referring to something which is a domain object in FusionAuth, but we are not explicitly referring to an object being created/updated in FusionAuth, we use lowercase.
```

2023-03-13 20:17 UTC, merged