blogpost: deploy FusionAuth on Digital Ocean
FusionAuth/fusionauth-site pull request #2049
Opened 2023-03-22 14:02 UTC by sixhobbits

2023-05-23 13:24 UTC, ColinFrick requested changes
I had to re-create the cluster, because FusionAuth 1-click installation kept failing. I don't know what caused this. After destroying the cluster and creating a new one, it worked flawlessly.

2023-05-23 13:24 UTC, ColinFrick commented on site/_posts/2023-03-30-digitalocean-oneclick-installation.md
> +You've now deployed a FusionAuth instance on a public Kubernetes cluster hosted on DigitalOcean. From here, you can [create an application](https://fusionauth.io/docs/v1/tech/core-concepts/applicatio
Please use relative links

2023-05-23 13:33 UTC, sixhobbits commented
> I had to re-create the cluster, because FusionAuth 1-click installation kept failing. I don't know what caused this. After destroying the cluster and creating a new one, it worked flawlessly.

@ColinFrick - I meant to mention that we had this problem too but couldn't reliably reproduce it or figure out why it was happening. Not sure if it is something that the DigitalOcean team would need to look into or if we should raise a bug on Fusionauth?

2023-06-12 07:51 UTC, ColinFrick commented
@mooreds the PR looks good to me, but it the deployment could fail sporadically (see https://github.com/FusionAuth/fusionauth-issues/issues/2297 ). How should we proceed?

2023-06-12 12:48 UTC, mooreds commented
Looks like 2297 is going to be addressed soon (it is in the backlog) so we can wait until it is fixed before publishing.

2023-08-22 18:16 UTC, bhalsey commented on site/_posts/2023-03-30-digitalocean-oneclick-installation.md
> +export SERVICE_IP=$(kubectl get svc --namespace fusionauth fusionauth -o jsonpath='{.status.loadBalancer.ingress[0].ip}') \
```suggestion
export SERVICE_IP=$(kubectl get svc --namespace fusionauth fusionauth -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```

Remove backslash at the end of the first line (consistent with other places this snippet occurs).  Or insert a semicolon before the backslash `; \`

2023-08-30 16:28 UTC, mooreds commented
Looks like we're good to go from a DO perspective.

2023-08-30 18:14 UTC, mooreds commented
Closing this, will deliver under https://github.com/FusionAuth/fusionauth-site/pull/2493

2023-08-30 18:14 UTC, closed without merging