support for existing password on password change
FusionAuth/fusionauth-site pull request #2066
Opened 2023-03-28 21:27 UTC by andrewpai

Admin UI and API doc changes for https://github.com/FusionAuth/fusionauth-issues/issues/1578

2023-03-30 17:57 UTC, spwitt requested changes
Alphabetize field documentation according to the field name. The current preference is to avoid extra line breaks unless they are required for formatting.

2023-04-20 23:02 UTC, mooreds commented on site/docs/v1/tech/apis/_generic-update-explanation-fragment.adoc
> +You must specify all of the properties of the {capitalized_object_name} when calling this API with the `PUT` HTTP method.
@andrewpai This is an existing convention. Spencer and I discussed changing this, but Brian and Daniel overruled us. You can view the conversation here: https://inversoft.slack.com/archives/C0407G6V5/p1653503200491019

2023-05-05 03:32 UTC, robotdan commented on site/docs/v1/tech/apis/_application-request-body.adoc
> +This setting has no effect when a self-service account form has not been set on the Application.
We should also mention this is only enforced with the form has a password field configured.

2023-05-05 03:35 UTC, robotdan commented on site/docs/v1/tech/apis/users.adoc
> +The one exception to this is with the password field. If you do not specify a password using the `PUT` method, the user's current password will be preserved and will not be deleted. A user's password
Did you mean to remove the previous copy? "The one exception to this.." seems like it should come after a previous statement which looks to be missing.

2023-05-05 03:36 UTC, robotdan commented on site/docs/v1/tech/core-concepts/applications.adoc
> +If set, a user will have to provide their current password when changing their password on the self-service account form. Note that a User self-service form must be selected for this setting to have
We should also mention that this only applies when the form has a password field configured.

2023-05-11 16:50 UTC, mooreds commented
@andrewpai ping.

2023-05-22 13:32 UTC, mooreds commented
Ooops, I didn't see this open PR, so I did it on Friday ( https://github.com/FusionAuth/fusionauth-site/pull/2190 ) because I kept getting API failed messages :( .

Sorry about the duplicate work.

2023-05-27 02:40 UTC, closed without merging