docs: migrate from Duende guide
FusionAuth/fusionauth-site pull request #2107
Opened 2023-04-19 18:32 UTC by sixhobbits

depends on:

- https://github.com/FusionAuth/fusionauth-import-scripts/pull/9
- https://github.com/FusionAuth/fusionauth-contrib/pull/11

2023-06-12 12:16 UTC, ColinFrick requested changes

2023-06-12 12:16 UTC, ColinFrick commented on site/docs/v1/tech/migration-guide/duende.adoc
> +$ ruby ./import.rb -f http://localhost:9011 -k '...' -u user-data.json
Could you add `-t '...'` to the command. I missed this on my first try, which caused the import.rb to crash with a non-descriptive error message:
```
Traceback (most recent call last):
	2: from ./import.rb:240:in `<main>'
	1: from ./import.rb:156:in `import'
./import.rb:156:in `+': no implicit conversion of nil into String (TypeError)
```

2023-06-13 12:20 UTC, rideam commented
@ColinFrick I pushed updates

2023-06-15 23:41 UTC, mooreds commented
@ColinFrick can you please re-review?

2023-06-19 12:00 UTC, ColinFrick approved these changes
LGTM

2023-06-20 14:50 UTC, mooreds commented
Closed under https://github.com/FusionAuth/fusionauth-site/pull/2257

2023-06-20 14:50 UTC, closed without merging