docs: Flask integration tutorial
FusionAuth/fusionauth-site pull request #2126
Opened 2023-04-28 11:56 UTC by sixhobbits

2023-05-05 23:22 UTC, mooreds requested changes
Really close. 

* need to add a flask row to docs/quickstarts/index.html (webapps section). I can take care of the logo, but please add the row.
* update example app to point to the new repo.

2023-05-05 23:22 UTC, mooreds commented on site/docs/v1/tech/tutorials/integrate-python-flask.md
> +```text
Moved this over to https://github.com/fusionauth/fusionauth-example-python-flask-guide

2023-05-05 23:22 UTC, mooreds commented on site/docs/v1/tech/tutorials/integrate-python-flask.md
> +import json
For these, we tend to put the whole file in at once, not breaking it down addition by addition.

This means you can use remote_include to pull in the entire file and you don't need to breakdown what is happening.

2023-05-09 22:42 UTC, rideam commented on site/docs/v1/tech/tutorials/integrate-python-flask.md
> +{% remote_include https://raw.githubusercontent.com/ritza-co/fusionauth-flask-integration/main/requirements.txt %}
@mooreds I have opened a PR [here](https://github.com/FusionAuth/fusionauth-example-python-flask-guide/pull/1) to update the example to use the latest version of fusionauth_client. So the change will reflect once that is merged. The includes are now pointing to that repo.

2023-05-10 22:51 UTC, merged