docs: Add documentation for Express.js API
FusionAuth/fusionauth-site pull request #2178
Opened 2023-05-17 18:59 UTC by ColinFrick

The example app is currently here: https://github.com/sonderformat-llc/fusionauth-example-express-api

Closes [#2201](https://github.com/FusionAuth/fusionauth-issues/issues/2201)

2023-06-15 23:46 UTC, mooreds commented
@ColinFrick can you double check this and make sure it and the example app are structured like the rails API quickstart? https://fusionauth.io/docs/v1/tech/tutorials/integrate-ruby-rails-api

If it is, we'll get it reviewed.

2023-06-19 08:53 UTC, ColinFrick commented
@mooreds I have updated the quickstart and app.

This is ready to be reviewed.

2023-06-21 03:12 UTC, mooreds commented
@vcampitelli can you please take a first pass?

2023-06-29 20:12 UTC, vcampitelli requested changes

2023-06-29 20:13 UTC, vcampitelli commented on site/_layouts/doc.liquid
> +                        <li {% if page.url == "/docs/v1/tech/tutorials/integrate-express-api.html" %}class="active"{% endif %}><a href="/docs/v1/tech/tutorials/integrate-express-api">Express.JS API</
@mooreds is that okay?

PS: I can rename the other "Express.js" article to "Express" so @ColinFrick can focus on this one

2023-07-03 12:13 UTC, ColinFrick commented on site/_layouts/doc.liquid
> +                        <li {% if page.url == "/docs/v1/tech/tutorials/integrate-express-api.html" %}class="active"{% endif %}><a href="/docs/v1/tech/tutorials/integrate-express-api">Express.JS API</
Fine with me.

Just FYI:
> In general, “Express” is preferred to “Express.js,” though the latter is acceptable.
https://expressjs.com/en/resources/glossary.html#express

2023-07-26 23:26 UTC, mooreds commented on site/docs/v1/tech/tutorials/integrate-express-api.md
> +{% include docs/integration/_intro-api.md %}
Fixed in same way.

2023-07-26 23:47 UTC, mooreds commented
Closing because this is done under #2358

2023-07-26 23:47 UTC, closed without merging