update react sdk add hosted backend warning
FusionAuth/fusionauth-site pull request #2279
Opened 2023-06-28 16:34 UTC by mooreds

Hosted backend pages sometimes send 403 errors, wanted to highlight that in the react tutorial.

2023-06-29 16:02 UTC, vcampitelli requested changes

2023-06-29 16:02 UTC, vcampitelli commented on site/_includes/docs/_hosted-backend-warning.md
> +* set up a [custom domain name for the FusionAuth Cloud instance](/docs/v1/tech/installation-guide/cloud#updating-with-existing-custom-domains) (limited to certain plans).
It seems that these links are being rendered incorrectly when the file is being included in `.md` vs `.adoc` files:

`.adoc`:
![adoc](https://github.com/FusionAuth/fusionauth-site/assets/1877191/fdba8b4b-a262-48dc-bfab-00d4f2001bdc)

`.md`: 
![md](https://github.com/FusionAuth/fusionauth-site/assets/1877191/479f8ee4-d0c5-40e1-aa2f-bd2f10c4a519)

I couldn't make them work in both files, so maybe we should have 2 `_hosted-backend-warning` files with each extension and different hyperlink syntax.

2023-06-30 00:38 UTC, mooreds commented
great catch, @vcampitelli ! I thought including it as markdown would work, but if I can't make it work, will have to split it up like you suggest.

2023-07-11 03:48 UTC, mooreds commented
@vcampitelli I was able to figure out a way to have both adoc and md files happy to include the warning. Please take a look.

2023-07-11 11:20 UTC, vcampitelli approved these changes

2023-07-11 13:35 UTC, merged