Extend users core page
FusionAuth/fusionauth-site pull request #2288
Opened 2023-07-03 12:50 UTC by ColinFrick

I added the Admin UI description and folded the `Segmenting Users` section into the relevant tab description.

Closes #1493

2023-08-03 01:04 UTC, mooreds requested changes
what about edit user drop down in upper right on the details screen? Can you please document that. 

please add to the 'table column' lists where appropriate, explanations of the magnifying glass and trash icons (and any other icons/actions)

2023-08-03 01:04 UTC, mooreds commented on site/docs/v1/tech/core-concepts/users.adoc
> +The source tab allows you to view the user in JSON format. This is useful for debugging and troubleshooting.
```suggestion
The source tab allows you to view the user account as read-only JSON. This is equivalent to retrieving the user via link:/docs/v1/tech/apis/users[the User API]. This is useful for debugging and troubleshooting.
```

2023-08-07 15:06 UTC, ColinFrick commented
@mooreds This is ready to re-review.

This depends on the https://github.com/FusionAuth/fusionauth-style/pull/30 PR, because the orange button color is not yet available. Should I change it to gray for now?

2023-08-08 11:49 UTC, mooreds commented
Closing, going to release under https://github.com/FusionAuth/fusionauth-site/pull/2413 with a few small changes. But in general, looks great and will be a huge help to folks navigating the FusionAuth admin UI.

2023-08-08 11:49 UTC, closed without merging