Add 1.46 release announcement
FusionAuth/fusionauth-site pull request #2289
Opened 2023-07-03 15:58 UTC by mooreds

2023-07-03 19:16 UTC, mark-robustelli commented on site/_posts/2023-06-30-announcing-fusionauth-1-46.md
> +description: This release includes a number of security fixes, improvements to the device grant, and improves the OIDC discovery endpoint.
If the subject is "This release" then "improvements to the device grant"  does not make sense and needs a verb.  If the subject is "This release includes" then "improves the OIDC..."  seems off.

2023-07-03 23:00 UTC, mark-robustelli requested changes

2023-07-12 16:08 UTC, mooreds commented on site/_posts/2023-07-12-announcing-fusionauth-1-46.md
> +All in all there are 26 issues, enhancements, and bug fixes included in the 1.46 release. As always, please see the [release notes](/docs/v1/tech/release-notes#version-1-46-0) for a full breakdown of
copy pasta. I think that with 1.45 (or a previous one), I was doing an announcement for multiple patch releases.

I'll update to use 1.46.0.

2023-07-12 16:11 UTC, mooreds commented on site/_posts/2023-07-12-announcing-fusionauth-1-46.md
> +Until this release, when there was a single FusionAuth tenant, the endpoint path was `/.well-known/openid-configuration`. The full URL would be something like `https://local.fusionauth.io/.well-known
Makes sense.

2023-07-12 17:11 UTC, merged