fi- 1469 updated info about smtp password not copying on duplicate
FusionAuth/fusionauth-site pull request #2292
Opened 2023-07-06 02:45 UTC by mark-robustelli

2023-07-06 17:47 UTC, mooreds commented
@mark-robustelli what is fi-1469? please provide a link to the issue.

2023-07-06 17:49 UTC, mark-robustelli commented
https://github.com/FusionAuth/fusionauth-issues/issues/1469

2023-07-06 18:05 UTC, mooreds requested changes

2023-07-06 18:05 UTC, mooreds commented on site/docs/v1/tech/core-concepts/tenants.adoc
> +image::list-of-tenants.png[List of Tenants,width=1200,role=shadowed]
No need for role of shadowed.

Please put this under the `site/assets/img/docs/core-concepts/` directory.

2023-07-06 18:05 UTC, mooreds commented on site/docs/v1/tech/core-concepts/tenants.adoc
> +** You cannot delete the Default tenant.
Please link to the limitations section here: https://fusionauth.io/docs/v1/tech/reference/limitations#default-configuration

2023-07-06 18:06 UTC, mooreds commented on site/docs/v1/tech/core-concepts/tenants.adoc
> +image::list-of-tenants.png[List of Tenants,width=1200,role=shadowed]
And make sure you run it through tinypng after cropping (I crop with the Preview App on the mac and that increases the size of the PNG).

2023-07-07 03:16 UTC, closed without merging

2023-07-07 03:17 UTC, mark-robustelli commented
deleting this branch due to the checkin with bad username.