brad publishes mark r's CIAM post...to master this time.
FusionAuth/fusionauth-site pull request #2393
Opened 2023-08-02 21:27 UTC by bradmccarty

2023-08-02 21:40 UTC, bradmccarty commented
This can close out https://github.com/FusionAuth/fusionauth-site/pull/2392

2023-08-03 00:07 UTC, mooreds requested changes
Minor changes.

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +author: Mark Robustelli
```suggestion
author: Alex Patterson
```

Alex wrote this.

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +## What is CIAM?
Article headers should be title cased:

```suggestion
## What Is CIAM?
```

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +### Benefits to using CIAM solutions
```suggestion
### Benefits To Using CIAM Solutions
```

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +## CIAM solutions
```suggestion
## CIAM Solutions
```

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +### Customer experience
```suggestion
### Customer Experience
```

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +### User experience
```suggestion
### User Experience
```

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +## What is the difference between CIAM and IAM?
```suggestion
## What Is The Difference Between CIAM and IAM?
```

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +## What are the essential elements of CIAM?
```suggestion
## What Are the Essential Elements Of CIAM?
```

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +## What are the Common Authentication Elements in CIAM?
```suggestion
## What Are the Common Authentication Elements In CIAM?
```

2023-08-03 00:07 UTC, mooreds commented on astro/src/content/articles/ciam/what-is-ciam.md
> +## Why choose FusionAuth?
```suggestion
## Why Choose FusionAuth?
```

2023-08-03 02:12 UTC, bradmccarty commented
Fixed your edits. Thanks @mooreds

2023-08-03 21:35 UTC, merged