Adding Android Quickstart
FusionAuth/fusionauth-site pull request #2415
Opened 2023-08-08 12:47 UTC by vcampitelli

There are some things that I wanted to check before we can actually merge this:

- [ ] Decide on the name: should it actually be "Java for Android"?
- [ ] I've named the sample repo as [`fusionauth-quickstart-android-java`](https://github.com/FusionAuth/fusionauth-quickstart-android-java) but the [Quickstart instructions](https://github.com/FusionAuth/fusionauth-example-template/blob/master/QUICKSTART-INSTRUCTIONS.md#the-tldr) expects `fusionauth-quickstart-LANGUAGE-FRAMEWORK-{api,web}`, so maybe I should append `-native`? I didn't because it seems redundant.
- [ ] The Issuer should match the instance URL, so the user should expose the instance with ngrok, update the Issuer and recreate asymmetric keys. Should I add these steps to the guide or create a simple script (probably add a command to the Node CLI) that does all that automatically?

2023-08-08 23:19 UTC, mooreds commented
> Decide on the name: should it actually be "Java for Android"?

How about "Android Java Quickstart"?

> I've named the sample repo as [fusionauth-quickstart-android-java](https://github.com/FusionAuth/fusionauth-quickstart-android-java) but the [Quickstart instructions](https://github.com/FusionAuth/fusionauth-example-template/blob/master/QUICKSTART-INSTRUCTIONS.md#the-tldr) expects fusionauth-quickstart-LANGUAGE-FRAMEWORK-{api,web}, so maybe I should append -native? I didn't because it seems redundant.

How about fusionauth-quickstart-java-android-native (or -mobile)? Either seem accurate.

> The Issuer should match the instance URL, so the user should expose the instance with ngrok, update the Issuer and recreate asymmetric keys. Should I add these steps to the guide or create a simple script (probably add a command to the Node CLI) that does all that automatically?

Hmmm. Can you have this be a config setting, where you stand up FusionAuth with ngrok, update a settings file someplace, then build the android app?

2023-08-11 12:24 UTC, vcampitelli commented
> How about "Android Java Quickstart"?

Done

> How about fusionauth-quickstart-java-android-native (or -mobile)? Either seem accurate.

Done

> Hmmm. Can you have this be a config setting, where you stand up FusionAuth with ngrok, update a settings file someplace, then build the android app?

What do you mean by "config setting"?

2023-08-11 12:48 UTC, mooreds commented
> What do you mean by "config setting"?

When I am building an android app, is there a corresponding config file, similar to `.env` for docker or php, where a user could set up the ngrok URL?

So I'm talking about build time configuration, not runtime configuration.

Does that make sense?

2023-08-11 19:45 UTC, vcampitelli commented
> When I am building an android app, is there a corresponding config file, similar to .env for docker or php, where a user could set up the ngrok URL?

Yes, it does. That's why I asked if it would be better to write these steps to the quickstart (expose the instance with ngrok, update the Issuer, recreate asymmetric keys, update settings file) or create a simple script to do all that.

2023-08-11 20:15 UTC, mooreds commented
>  That's why I asked if it would be better to write these steps to the quickstart (expose the instance with ngrok, update the Issuer, recreate asymmetric keys, update settings file) or create a simple script to do all that.

Ah, okay. Since this won't be done typically (people will probably work through the quickstart once, not multiple times) I think documentation is fine.

2023-08-14 16:00 UTC, vcampitelli commented
1. I've pushed an additional step on configuring issuer and regenerating JWT keys.
2. I've also created a `<IconButton>` component to render UI-like buttons, like we had with markdown/asciidocs, and updated `DocsDevREADME` with instructions.
![icons](https://github.com/FusionAuth/fusionauth-site/assets/1877191/719bffe8-2a54-41a2-a339-b3afeda8d499)
3. As discussed with @mooreds, I didn't recreate the exact same Changebank theme as things aren't that easy with Android, but I used the same color, texts and functionality.

2023-09-06 07:16 UTC, ColinFrick requested changes
After completing the tutorial the app didn't start. I had to remove following files first:
- `app/java/io/fusionauth/app/BrowserSelectionAdapter.java`
- `app/res/layout/browser_selector_layout.xml`

<img width="1047" alt="CleanShot 2023-09-06 at 09 19 06@2x" src="https://github.com/FusionAuth/fusionauth-site/assets/5517677/7ce8b9ad-6172-4bb6-9d14-f03e5debf3a0">

2023-09-11 13:05 UTC, vcampitelli commented on astro/src/content/quickstarts/quickstart-android-java.mdx
> +* Your example username is `richard@example.com` and the password is `password`.
Sorry, I missed a `push` with the right kickstart and CSS files. Done now.

2023-09-11 13:12 UTC, mooreds commented
@vcampitelli is this ready for @ColinFrick to re-review?

2023-09-11 14:25 UTC, vcampitelli commented
Yup, just pushed the kickstart file that was missing.

Can you please review it again @ColinFrick ?

2023-09-12 07:22 UTC, ColinFrick approved these changes
@vcampitelli Quick start looks good. I have found a typo in the kickstart.json.

See https://github.com/FusionAuth/fusionauth-quickstart-java-android-native/commit/8a38be203ef670ae586115ce9e1ad3d4d35e8940#r127101206

2023-09-14 17:39 UTC, vcampitelli commented
Done! Thanks @ColinFrick 

@mooreds this is now ready for you to review

2023-10-10 21:32 UTC, mooreds approved these changes

2023-10-10 21:34 UTC, merged