Mooreds/add stub user guide
FusionAuth/fusionauth-site pull request #2451
Opened 2023-08-15 17:14 UTC by mooreds

This guide walks you through setting up an anonymous/shadow user system with FusionAuth APIs.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205273462533518

2023-09-13 20:39 UTC, mark-robustelli requested changes
Man this is cool.  Just a couple of changes and a few suggestions.  Some of the links were in the new format.

I did have an issue with the [fusionauth-example-anonymous-user](https://github.com/FusionAuth/fusionauth-example-anonymous-user) repo.  I opened an [issue](https://github.com/FusionAuth/fusionauth-example-anonymous-user/issues) in that repo for it.  The app seems to work.

2023-09-13 20:39 UTC, mark-robustelli commented on site/docs/v1/tech/guides/anonymous-user.adoc
> +Make sure that you always confirm the user owns the email address which they are entering. Otherwise, a malicious actor could enter any email address, which may lead to unwanted escalation.
This is the same as line 175, I think it works better here.

2023-09-13 20:39 UTC, mark-robustelli commented on site/docs/v1/tech/guides/anonymous-user.adoc
> +Make sure that you always confirm the user owns the email address which they are entering. Otherwise, a malicious actor could enter any email address, which may lead to unwanted escalation.
```suggestion
```

2023-09-13 20:39 UTC, mark-robustelli commented on site/docs/v1/tech/guides/anonymous-user.adoc
> +There are two webhook events you could listen for and process cleanup after.
```suggestion
There are two link:/docs/v1/tech/events-webhooks/[webhook] events you could listen for and process cleanup after.
```

2023-09-13 20:39 UTC, mark-robustelli commented on site/docs/v1/tech/guides/anonymous-user.adoc
> +This guide will use the latter option. You'll need to create and register the webhook, which can be done via admin UI or API.
```suggestion
This guide will use the latter option. You'll need to link:/docs/v1/tech/events-webhooks/#add-webhook[create and register the webhook], which can be done via admin UI or API.
```

2023-09-13 20:43 UTC, mark-robustelli commented on site/docs/v1/tech/guides/anonymous-user.adoc
> +In this guide, you'll be creating anonymous users whenever a user visits a page to watch videos. The videos are about ChangeBank, the global leader in making change.
Just realized there is only on video on the page so need to change to singular.
```suggestion
In this guide, you'll be creating anonymous users whenever a user visits a page to watch the video. The video is about link:https://www.youtube.com/watch?v=CXDxNCzUspM[ChangeBank], the global leader in making change.
```

2023-09-13 22:54 UTC, mooreds commented
Added note re: https://github.com/FusionAuth/fusionauth-example-anonymous-user/issues/1 @mark-robustelli

2023-09-20 02:57 UTC, mark-robustelli approved these changes
LGTM!

2023-09-21 02:17 UTC, merged