Quickstart Angular
FusionAuth/fusionauth-site pull request #2478
Opened 2023-08-22 12:17 UTC by escii

Creating a Quickstart for Angular

Closes Issue https://github.com/FusionAuth/fusionauth-issues/issues/2395

2023-08-31 17:15 UTC, alex-fusionauth commented
> 

Create new repo https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web

2023-08-31 19:32 UTC, alex-fusionauth requested changes

2023-08-31 19:32 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-javascript-angular-web.mdx
> +npx ng new changebank && cd changebank
```suggestion
npx @angular/cli new changebank && cd changebank
```

2023-08-31 19:32 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-javascript-angular-web.mdx
> +* Your client Id is `e9fdb985-9173-4e01-9d73-ac2d60d1dc8e`.
```suggestion
* Your Client Id is `e9fdb985-9173-4e01-9d73-ac2d60d1dc8e`.
```

2023-08-31 19:32 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-javascript-angular-web.mdx
> +* Your client secret is `super-secret-secret-that-should-be-regenerated-for-production`.
```suggestion
* Your Client Secret is `super-secret-secret-that-should-be-regenerated-for-production`.
```

2023-08-31 19:32 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-javascript-angular-web.mdx
> +Next, you'll need to configure the SDK with your FusionAuth URL and client ID. You can do this by adding the following to your `src/app/app.module.ts` file inside the `imports: [ ]` part:
```suggestion
Next, you'll need to configure the SDK with your FusionAuth URL and Client Id. You can do this by adding the following to your `src/app/app.module.ts` file inside the `imports: [ ]` part:
```

2023-08-31 19:32 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-javascript-angular-web.mdx
> +npx ng new changebank && cd changebank
Once the package.json is installed you can then use `ng`

2023-08-31 19:32 UTC, alex-fusionauth commented on astro/src/diagrams/quickstarts/login-after-sdk.astro
Does it make sense to update `astro/src/diagrams/quickstarts/login-after.astro` so that this matches the rest of the quickstarts? Is there something that is wouldn't make sense with the added section?

```
 FusionAuth ->> User: Go to Redirect URI
    User ->> App: Request the Redirect URI
    App ->> FusionAuth : Is User Authenticated?
```

2023-08-31 19:32 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-javascript-angular-web.mdx
> +<RemoteCode url="https://raw.githubusercontent.com/sonderformat-llc/fusionauth-quickstart-javascript-angular-web/main/complete-application/src/app/app.component.html"
We are also including a functioning page for `make-change` link/route.

You can find an example of the logic in the Next.js example app.
https://github.com/FusionAuth/fusionauth-quickstart-javascript-nextjs-web/blob/main/complete-application/src/components/MakeChangeForm.tsx

Or a crude example in
https://github.com/FusionAuth/fusionauth-quickstart-javascript-express-web/tree/fix-make-change

2023-09-08 14:44 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-javascript-angular-web.mdx
> +<RemoteCode url="https://raw.githubusercontent.com/sonderformat-llc/fusionauth-quickstart-javascript-angular-web/main/complete-application/src/app/app.component.html"
Requested some changes for make-change to match our other examples

https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web/pull/2#pullrequestreview-1617650088

2023-09-11 23:32 UTC, alex-fusionauth approved these changes

2023-09-13 03:07 UTC, mooreds commented
Closing under https://github.com/FusionAuth/fusionauth-site/pull/2527

2023-09-13 03:07 UTC, closed without merging