Quickstart flutter mobile
FusionAuth/fusionauth-site pull request #2514
Opened 2023-09-08 15:32 UTC by sixhobbits

2023-09-18 19:33 UTC, alex-fusionauth commented
Moved to new Repo
https://github.com/FusionAuth/fusionauth-quickstart-flutter-native

2023-09-18 21:10 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-flutter-native.mdx
> +### Set Up A Public URL For FusionAuth
Could we add some verbiage here to include this as an easy guide?
https://fusionauth.io/docs/v1/tech/developer-guide/exposing-instance

Then include this script
```shell
ngrok http --request-header-add 'X-Forwarded-Port:443' 9011
```

2023-09-18 21:12 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-flutter-native.mdx
> +At the top of the file, change the `FUSIONAUTH_DOMAIN` constant to the public URL for your FusionAuth instance (the URL you used when configuring it).
Include link back to `/#set-up-a-public-url-for-fusionauth` for clarity.

2023-09-19 12:21 UTC, rideam commented
@alex-fusionauth I opened a PR here https://github.com/FusionAuth/fusionauth-quickstart-flutter-native/pull/1 to fix the rounding issue

2023-09-19 13:20 UTC, alex-fusionauth commented
> @alex-fusionauth I opened a PR here [FusionAuth/fusionauth-quickstart-flutter-native#1](https://github.com/FusionAuth/fusionauth-quickstart-flutter-native/pull/1) to fix the rounding issue

awesome, merged :D

2023-09-19 13:22 UTC, alex-fusionauth approved these changes

2023-09-19 15:07 UTC, alex-fusionauth requested changes
@sixhobbits can we get an additional page added to the app?

We typically have an account page and make-change page when a user is logged in to show that you can secure both.

2023-09-20 01:18 UTC, rideam commented
@alex-fusionauth I opened a PR https://github.com/FusionAuth/fusionauth-quickstart-flutter-native/pull/2 to add separate account and make-change pages

2023-10-03 14:41 UTC, alex-fusionauth commented
> @alex-fusionauth I opened a PR [FusionAuth/fusionauth-quickstart-flutter-native#2](https://github.com/FusionAuth/fusionauth-quickstart-flutter-native/pull/2) to add separate account and make-change pages

Sorry missed this @rideam. Looks good and merged.

2023-10-03 14:44 UTC, alex-fusionauth approved these changes

2023-11-10 15:36 UTC, escii reviewed
This guide is definitely not for beginners. Prior mobile development knowledge is essential, and running it in emulators demands a substantial amount of RAM. Overall, it's a great guide. Just found some possible gramatical changes.

2023-11-10 15:36 UTC, escii commented on astro/src/content/quickstarts/quickstart-flutter-native.mdx
> +From the list of emulators or devices that is returned, choose the one you want the code to run in. Stay in this directory for the rest of this tutorial.
```suggestion
From the list of emulators or devices that can be used, choose the one that you want to run the code on.
Stay in this directory for the rest of this tutorial.
```

2023-11-10 15:36 UTC, escii commented on astro/src/content/quickstarts/quickstart-flutter-native.mdx
> +Start with getting FusionAuth up and running and creating a Flutter application.
```suggestion
Start by getting FusionAuth up and running and creating a Flutter application.
```

2023-11-10 15:36 UTC, escii commented on astro/src/content/quickstarts/quickstart-flutter-native.mdx
> +In general, you would introduce FusionAuth to normalize and consolidate user data, making it consistent and up-to-date and offloading your login security and functionality to FusionAuth.
```suggestion
In general, you would introduce FusionAuth to normalize and consolidate user data, ensuring consistency and reliable, while offloading your login security and functionality to FusionAuth.
```

2023-11-13 16:16 UTC, merged