Quickstart javascript remix
FusionAuth/fusionauth-site pull request #2515
Opened 2023-09-08 16:02 UTC by sixhobbits

* Please ignore the django-related commits in the first half - they are already in master
* Not sure if types.d.ts file should be in .gitignore as it seems autogenerated?

2023-09-08 19:08 UTC, vcampitelli requested changes

2023-09-08 19:08 UTC, vcampitelli commented on astro/src/content/quickstarts/quickstart-javascript-remix-web.mdx
> +Start the Remix server.
```suggestion
Start the Remix server from the root `mysite` directory.
```

Or something like that.

2023-09-12 11:48 UTC, rideam commented on astro/src/content/quickstarts/quickstart-javascript-remix-web.mdx
> +If you have not worked with React before, there are a few differences from normal HTML to note:
switched the paragraphs

2023-09-12 11:49 UTC, rideam commented on astro/src/content/quickstarts/quickstart-javascript-remix-web.mdx
> +In the line `new Authenticator<User>`, you can specify which user details you want to keep in the session. This example uses a single string containing the user's email, but you could define an objec
removed the extra information

2023-09-12 11:51 UTC, rideam commented on astro/src/content/quickstarts/quickstart-javascript-remix-web.mdx
> +Choose the following options:
added a line for the user to allow installation

2023-09-14 18:13 UTC, vcampitelli approved these changes

2023-09-14 18:13 UTC, vcampitelli commented
@mooreds this is ready for you to review

2023-10-21 10:56 UTC, escii commented
looks good, nothing to complain about.
I think this is ready to be published @mooreds

2023-10-21 11:00 UTC, escii approved these changes

2023-10-21 12:18 UTC, merged