Quickstart ruby on rails api
FusionAuth/fusionauth-site pull request #2528
Opened 2023-09-13 16:52 UTC by alex-fusionauth

2023-09-15 21:41 UTC, mark-robustelli requested changes
@alex-fusionauth Not so much finished or changes requested, but I am stuck and can't get past the GemFile update.  Let's make some time Monday to go over.

2023-09-15 21:41 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +Once this is complete you will see a new directory called `your-application` with several sub directories.
```suggestion
Once this is complete, you will see a new directory called `your-application` with several sub directories.
```

2023-09-15 21:41 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +```
This does not work for me, I get an Error.
![Screenshot 2023-09-15 at 2 39 10 PM](https://github.com/FusionAuth/fusionauth-site/assets/137117976/a98722c1-ea63-4556-91fe-becd4f88726c)

2023-09-20 01:37 UTC, mark-robustelli requested changes
Also, is there another file that we need to deprecate?

2023-09-20 01:37 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +Create a new file to hold your environment variables, directly in the `complete-application` directory called `.env.development`. This new file has two variables that are used to call your FusionAuth
Should this be in the `complete-application` directory or the `your-application` directory.  Assuming it should be the `your-application` directory.

2023-09-20 01:37 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +Create a new file to hold your environment variables, directly in the `complete-application` directory called `.env.development`. This new file has two variables that are used to call your FusionAuth
```suggestion
Create a new file to hold your environment variables directly in the `your-application` directory called `.env.development`. This new file has two variables that are used to call your FusionAuth instance `FUSIONAUTH_LOCATION` and `CLIENT_ID`, with the values that match below.
```

2023-09-20 01:37 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +There are [several ways to acquire a token](/docs/v1/tech/oauth/) in FusionAuth, but for this example you will use the [Login API](/docs/v1/tech/apis/login) to keep things simple.
Should mention here that you should open a new terminal window and will be using it window for the commands the following commands. The server is running in the terminal window I was using.

2023-09-20 01:37 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +We can make change using 20 quarters 1 dimes 0 nickels 2 pennies
I get

{"total":0.0,"message":"We can make change using 20 quarters 1 dimes 0 nickels 2 pennies"}

Notice the Total is 0.

2023-09-20 01:37 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +We can make change using 12 quarters 2 dimes 0 nickels 4 pennies
I get  same

`{"total":0.0,"message":"We can make change using ....`

Notice the Total is 0.

2023-09-21 18:24 UTC, alex-fusionauth commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +```
This feels like more of an issue on how you have Ruby installed I think.

2023-09-21 20:50 UTC, mark-robustelli requested changes
A few more minor updates, but ran pretty smoothly for me.  No need to re-request my review, go ahead and pass to Dan when you make the updates.

2023-09-21 20:50 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +Create a new file to hold your environment variables directly in the `your-application` directory called `.env.development`. This new file has two variables that are used to call your FusionAuth inst
```suggestion
Create a new file to hold your environment variables directly in the `your-application` directory called `.env.development`. You will need to add two variables that are used to call your FusionAuth instance `FUSIONAUTH_LOCATION` and `CLIENT_ID`, with the values that match below.
```

2023-09-21 20:50 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +Utilizing the enviroment variables you just added we can now setup JSON Web Token (JWT) based authentication. Create a new file  `config/initializers/jwt_rack.rb`. This initializer is used to hold co
```suggestion
Utilizing the enviroment variables you just added, you can now setup JSON Web Token (JWT) based authentication. Create a new file  `config/initializers/jwt_rack.rb`. This initializer is used to hold configuration settings that are made after all of the frameworks and plugins are loaded. 
```

2023-09-21 20:50 UTC, mark-robustelli commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +Your response should look like:
It may be worth noting here that you get the 401 Unauthorized response with the following message.

2023-10-03 22:00 UTC, mooreds requested changes
For https://github.com/fusionauth/fusionauth-quickstart-ruby-on-rails-api/

* need to update ports on the README (I did)
* Need to update the curl command to be a cookie

For the site:

* please update the cloudfront handler to point to the new quickstart (from the old ruby on rails API URL). We'll also need to archive the old API repo, as documented here: https://github.com/FusionAuth/fusionauth-example-template/blob/master/QUICKSTART-INSTRUCTIONS.md#deprecating-existing-repositories
* please remove the old quickstart (under docs/v1/tech/tutorials)

2023-10-09 19:21 UTC, mooreds requested changes

2023-10-09 19:21 UTC, mooreds commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +We can make change using 20 quarters 1 dimes 0 nickels 2 pennies
Please have this be JSON, as specified in the quickstart instructions.

2023-10-09 19:21 UTC, mooreds commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +We've called the police!
Please have this be JSON.

2023-10-09 19:21 UTC, mooreds commented on astro/src/content/quickstarts/quickstart-ruby-on-rails-api.mdx
> +We can make change using 12 quarters 2 dimes 0 nickels 4 pennies
Please have this be JSON

2023-10-10 18:44 UTC, mooreds approved these changes
No need for a final review, thanks!

2023-10-10 22:23 UTC, merged