Anonymous user blog post
FusionAuth/fusionauth-site pull request #2536
Opened 2023-09-15 23:52 UTC by mooreds

2023-09-21 17:45 UTC, alex-fusionauth requested changes
- Image update, maybe
- I couldn't get the actual program to update me from anonymous, but I am probably doing something wrong.
- minor text updates

2023-09-21 17:45 UTC, alex-fusionauth commented on astro/public/img/blogs/anonymous-user/anonymous-user-in-admin-screen.png
<img width="1192" alt="Screenshot 2023-09-21 at 1 37 48 PM" src="https://github.com/FusionAuth/fusionauth-site/assets/139158618/9031c633-46d8-4fd8-b6ae-48ba7f8ed979">

just added
<img width="172" alt="image" src="https://github.com/FusionAuth/fusionauth-site/assets/139158618/0a2fbd1d-2856-4f12-867e-0921ff6070f1">

2023-09-22 11:59 UTC, mooreds commented on astro/src/content/blog/anonymous-user.mdx
> +> any information that relates to an identified or identifiable living individual. Different pieces of information, which collected together can lead to the identification of a particular person, als
This is quoting from the previously linked doc.

2023-09-22 12:17 UTC, mooreds commented on astro/public/img/blogs/anonymous-user/anonymous-user-in-admin-screen.png
Filed an issue about this. https://github.com/FusionAuth/fusionauth-issues/issues/2482

Agree we should fix this, but would rather have the picture be true to what the user will see right now.

2023-09-22 16:52 UTC, alex-fusionauth approved these changes

2023-09-22 16:52 UTC, alex-fusionauth commented
LGTM, approved 😄

2023-10-02 14:10 UTC, merged