adding dotnet template blog
FusionAuth/fusionauth-site pull request #2581
Opened 2023-10-11 14:15 UTC by mark-robustelli

2023-10-11 19:02 UTC, alex-fusionauth requested changes
Few grammatical thoughts / changes.

Working through the technical side was pretty straight forward, just one call out about the insecure https.

2023-10-11 19:43 UTC, mark-robustelli commented on astro/src/content/blog/dotnet-templates.mdx
> +Of course, to effectively use these templates you will need an instance of FusionAuth to bang against. If you already have an instance set up, you likely know the settings you will need. If you do no
```suggestion
Of course, to effectively use these templates you will need an instance of FusionAuth to bang against. If you already have an instance set up, you likely know the settings you will need. If you do not have an instance to point to, don't fear. You can download an instance and have it up and running in no time assuming you have Docker installed. Simply clone the [fusionauth-example-client-libraries](https://github.com/FusionAuth/fusionauth-example-client-libraries/tree/main/dotnet/templates) info, and spin up the Docker instance using the following command.
```

2023-10-11 20:20 UTC, mark-robustelli commented on astro/src/content/blog/dotnet-templates.mdx
> +*Templates for nothin' and your security for free.*
Going for Dire Straits reference.  To obscure?

2023-10-11 20:21 UTC, mark-robustelli commented on astro/src/content/blog/dotnet-templates.mdx
> +Literally. The [FusionAuth Templates for Microsoft .NET](https://marketplace.visualstudio.com/items?itemName=FusionAuth.FusionAuthVSTemplates) are free to use and so is the self-hosted [Community Pla
If I ditch the first line, then I'll alter this.

2023-10-11 20:40 UTC, mark-robustelli commented on astro/src/content/blog/dotnet-templates.mdx
> +You can open a browser and go to [https://localhost:5001](https://localhost:5001). Log in using the username `admin@example.com` and the password `password`.
@alex-fusionauth , can you run 
`dotnet dev-certs https --check` 
and see if you have the dev-certs installed?  If not you may be able to run
`dotnet dev-certs https --trust`

as described here: https://stackoverflow.com/questions/64017267/dotnet-dev-certs-certificate-not-trusted

If that works, I will add the info.

2023-10-12 18:19 UTC, alex-fusionauth commented on astro/src/content/blog/dotnet-templates.mdx
> +*Templates for nothin' and your security for free.*
https://www.youtube.com/watch?v=wTP2RUD_cL0

2023-10-12 18:26 UTC, alex-fusionauth commented on astro/src/content/blog/dotnet-templates.mdx
> +You can open a browser and go to [https://localhost:5001](https://localhost:5001). Log in using the username `admin@example.com` and the password `password`.
did you switch the port to 5000 localhost?

2023-10-26 16:15 UTC, merged