Blog: FusionAuth on Fly.io
FusionAuth/fusionauth-site pull request #2604
Opened 2023-10-23 19:36 UTC by alex-fusionauth

2023-10-25 01:14 UTC, mark-robustelli requested changes
Overall, I think it is a good start.  There are a few confusing things we should talk through when you get a chance.

2023-10-25 01:14 UTC, mark-robustelli commented on astro/src/content/blog/fusionauth-on-fly-io.mdx
> +```toml
I don't think you need the original, you could just say to update it with the new values and then you can explain what you change.

2023-10-25 01:14 UTC, mark-robustelli commented on astro/src/content/blog/fusionauth-on-fly-io.mdx
> +fly deploy
think I went out of order here and should have said No to the deploy above.

wait...think I figured it out.  will keep going.

2023-10-25 01:14 UTC, mark-robustelli commented on astro/src/content/blog/fusionauth-on-fly-io.mdx
> +flyctl secrets set DATABASE_URL=jdbc:postgresql://fusion-fly-db.internal:5432/postgres POSTGRES_USER=postgres POSTGRES_PASSWORD=vGrUf0wysPLwQFc DATABASE_USERNAME=fusionauth DATABASE_PASSWORD=hkaLBM3R
I tried to do this, but think there is something goofed up with the name.  Let's take some time and go through this.

2023-10-25 01:14 UTC, mark-robustelli commented on astro/src/content/blog/fusionauth-on-fly-io.mdx
> +app = "fusion-fly"
Ah, after playing, I had to update this to make sure it is my app name.  Thing this needs to be more clear.

2023-10-25 01:14 UTC, mark-robustelli commented on astro/src/content/blog/fusionauth-on-fly-io.mdx
> +Now your FusionAuth application should be up and running at your website like `https://fusion-fly.fly.dev/`.
couldn't get it to run :(

2023-10-29 20:13 UTC, alex-fusionauth commented on astro/src/content/blog/fusionauth-on-fly-io.mdx
> +Fly.io does not currently support using `docker compose` so you will need to create a `Dockerfile` using the below command.
adjusted in the new "What is FLy.io" section

2023-10-30 20:04 UTC, mark-robustelli approved these changes
I was able to get this to run, so that is good and followed enough to do that.  However.  I am still not 100% sure I understand everything. I know this is not a step by step type quickstart. I may not be your target audience so I would have someone else look it over that may be closer to the audience you are trying to aim for.

2023-11-09 15:09 UTC, merged