1.48 post
FusionAuth/fusionauth-site pull request #2634
Opened 2023-11-03 03:27 UTC by mooreds

2023-11-07 19:07 UTC, mark-robustelli requested changes
Overall looks good, a couple of suggestions though.  Also, note the check is not passing for the full url.  It's probably the same thing others are experiencing.

2023-11-07 19:58 UTC, mooreds commented on astro/src/content/blog/announcing-fusionauth-1-48.mdx
> +Previous to this release, there was a limit on the number of user or entity search results. You could only get 10,000 users or entities in each search response. If you had more than that, which many
Hmm. It looks like only the API, but not sure if that is a bug.

2023-11-14 21:15 UTC, mooreds commented on astro/src/content/blog/announcing-fusionauth-1-48.mdx
> +image: /img/blogs/release-1-48/fusionauth-1-48.png
Added now.

2023-11-15 00:31 UTC, mark-robustelli approved these changes
LGTM

2023-11-20 16:00 UTC, merged