Bradm/seo updates 2
FusionAuth/fusionauth-site pull request #2712
Opened 2023-12-05 19:06 UTC by bradmccarty

More SEO updates, per our SEO/backlinks folks at Userp.

2023-12-07 23:07 UTC, mooreds commented
@bradmccarty do you need someone to review?

2023-12-08 16:28 UTC, mark-robustelli requested changes
Mostly comments and suggestions.  1 extra space that does need to be removed.

2023-12-08 16:28 UTC, mark-robustelli commented on astro/src/content/articles/identity-basics/magic-links.md
> +The comparison between the traditional login process using passwords and magic link authentication is both valid and  pertinent. Let’s explore why magic links might be a superior choice for enhancing
```suggestion
The comparison between the traditional login process using passwords and magic link authentication is both valid and pertinent. Let’s explore why magic links might be a superior choice for enhancing the authentication process.
```

2023-12-11 15:52 UTC, bradmccarty commented on astro/src/content/articles/authentication/multi-factor-authentication.md
> +### Inherence: Who You Are
This came from the SEO folks. I'm familiar, but I think this is google-centric.

2023-12-11 15:52 UTC, bradmccarty commented on astro/src/content/articles/authentication/multi-factor-authentication.md
> +As more of our lives move online, multi-factor authentication (MFA) becomes increasingly important as a way of keeping our accounts secure. As a user, you know you should enable MFA on any accounts c
This was a suggestion from the SEO folks. My guess is that they saw some cannibalism in search performance away from this page.

2023-12-11 15:54 UTC, bradmccarty commented
@mark-robustelli Addressed the changes, but it's still showing a blocked merge. Not sure why.

2023-12-11 20:02 UTC, mark-robustelli approved these changes

2023-12-11 20:02 UTC, mark-robustelli commented
@bradmccarty try to merge now.  I had to approve after you made the change.

2023-12-11 20:10 UTC, merged