feature(Blog - Best Practices for OAuth in Mobile Apps)
FusionAuth/fusionauth-site pull request #2783
Opened 2023-12-21 18:53 UTC by alex-fusionauth

2023-12-26 17:41 UTC, mark-robustelli requested changes

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +- You own everything
```suggestion
- You own everything

```

There is no line break and cons got shoved together
![Screenshot 2023-12-26 at 10 18 12 AM](https://github.com/FusionAuth/fusionauth-site/assets/137117976/b5fa3c53-7c39-4474-b4cf-4a06e8672e66)

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +> A quick not here we have a great article on [Avoiding Authentication System Lock-In](/articles/authentication/avoid-lockin).
Should you use the `<Aside>` like in the docs here?

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +- Leverage auth server
Could add something here like if using a provider, the provider is responsible for login attacks and that sort of thing.

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +> "The idea of having one central place where you can control who has access to which applications makes more sense. The more applications you have, the more a central identity store makes sense."
same not about `<Aside>`

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +We start by registering our app client in the identity provider and getting a *client ID*:
```suggestion
We start by registering our app client in the identity provider and getting a *client Id*:
```

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +1. App requests a login page from the ID provider
```suggestion
1. App requests a login page from the Id provider
```

change all IDs to Id

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +3. App receives standard ID and access tokens
```suggestion
3. App receives standard Id and access tokens
```

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +To initialize this, the app makes a request:
```suggestion
To initialize this, the app makes a request like this:
```

just a suggestion since it is an example.

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +- Apps should verify the signature and claims
```suggestion
- Apps should verify the signature and other security claims
```
not really going to be able to verify claims like name and user Id

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +- They contain *claims* like user ID, name, email
```suggestion
- They contain *claims* like user Id, name, email
```

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +
https only
don't pass in url or query strings

2023-12-26 17:41 UTC, mark-robustelli commented on astro/src/content/blog/best-practices-for-oauth-in-mobile-apps.mdx
> +Using OAuth and OIDC enables secure sign-on flows while accelerating development. By following the practices outlined here around protected tokens and platform-specific guidelines, native apps can bu
```suggestion
Using OAuth and OIDC enables secure sign-on flows while accelerating development. By following the practices outlined here around protected tokens and platform-specific guidelines, native apps can build robust Id management.
```

2024-01-09 17:42 UTC, mark-robustelli approved these changes
LGTM

2024-01-09 17:43 UTC, mooreds commented
:shipit:

2024-01-09 17:43 UTC, mooreds commented
Actually, looks like there's an issue with the selected categories.

2024-01-10 16:51 UTC, merged