Add protecting api blog
FusionAuth/fusionauth-site pull request #2865
Opened 2024-01-31 00:29 UTC by mooreds

Questions:

* is this better to split up into two blog posts (one about centralized/decentralized, one about first/third party)
* is the term 'central authority' useful, or should I change it
* any transitions seem abrupt or don't make sense

2024-01-31 19:42 UTC, alex-fusionauth requested changes
- is this better to split up into two blog posts (one about centralized/decentralized, one about first/third party)
-- No I like this all in one
- is the term 'central authority' useful, or should I change it
-- yes it is useful and very understandable in the charts
- any transitions seem abrupt or don't make sense
- is it obvious how to change the CSS for the parallel sequence diagrams? I couldn't figure it out
-- I don't like the red at all, I am also unclear on what the `par` keyword is and its hidden on the diagram

Added a CSS question for Andy
https://inversoft.slack.com/archives/C02CR2M6SRK/p1706729482035529

2024-01-31 19:42 UTC, alex-fusionauth commented on astro/src/content/blog/protecting-your-api.mdx
> +With such a platform in mind, Pied Piper needs to authenticate not just the API requester, but also control access in a more sophisticated way, based on what each service needs. For example, the Appl
```suggestion
With such a platform in mind, Pied Piper needs to authenticate not just the API requester, but also control access in a more sophisticated way, based on what each service needs. For example, the Apple Watch client needs to be able to read and write todos, but the analytics service only needs to be able to read them.
```

2024-01-31 19:42 UTC, alex-fusionauth commented on astro/src/content/blog/protecting-your-api.mdx
> +Spend some time up front thinking about what scopes make sense for your API. You want them to:
```suggestion
Spend some time upfront thinking about what scopes make sense for your API. You want them to:
```

2024-01-31 19:42 UTC, alex-fusionauth commented on astro/src/content/blog/protecting-your-api.mdx
> +You should think about whether to use a centralized API key verification system or decentralized verification. The centralized option requires constant communication between the consumers of API keys
```suggestion
You should think about whether to use a centralized API key verification system or decentralized verification. The centralized option requires constant communication between the consumers of API keys, the systems serving the API, and the central authority issuing API keys, all to ensure the validity of the keys. 
```

2024-02-01 15:29 UTC, bradmccarty reviewed
This is good to go from an SEO perspective @mooreds

2024-02-01 17:44 UTC, mooreds commented on astro/src/content/blog/protecting-your-api.mdx
> +Authorization can be done in a number of ways, including role-based access control (RBAC), attribute-based access control (ABAC), and relationship-based access control (ReBAC). Authorization decision
Agreed, but our primary solution for ABAC and ReBAC is "use an authorization server" like Cerbos or Permit.

2024-02-01 21:54 UTC, alex-fusionauth approved these changes
I would still rock a different image, but the rest looks good. Nice work on the CSS update.

2024-02-05 15:53 UTC, merged