adding forgerock migration
FusionAuth/fusionauth-site pull request #2874
Opened 2024-02-05 16:27 UTC by mark-robustelli

The code link will not work until [the import script pull request](https://github.com/FusionAuth/fusionauth-import-scripts/pull/14) is merged.

2024-02-06 22:27 UTC, alex-fusionauth requested changes
Main thing is making sure we are clear on import vs. export
The json vs. csv as well

I was able to walk through and run it after I fixed my API key perms

2024-02-06 23:40 UTC, mark-robustelli commented on astro/src/content/docs/lifecycle/migrate-users/bulk/forgerock.mdx
> +```shell title="Forgerock Export Script Help Results"
Yes, copy and paste error.  Fixed

2024-02-06 23:45 UTC, mark-robustelli commented on astro/src/content/docs/lifecycle/migrate-users/bulk/forgerock.mdx
> +    -u, --users-file USERS_FILE      The exported json user data file from Forgerock. Defaults to out.csv.
Updated.

2024-02-06 23:55 UTC, mark-robustelli commented on astro/src/content/docs/lifecycle/migrate-users/bulk/forgerock.mdx
> +```shell title="Import script output"
added

2024-02-07 00:05 UTC, mark-robustelli commented
Made the changes, please let me know if there is anything else.  Thanks.

2024-02-07 16:48 UTC, alex-fusionauth approved these changes
🛳️ it

2024-02-08 14:59 UTC, merged