Docs: add device limit guide
FusionAuth/fusionauth-site pull request #2889
Opened 2024-02-14 10:55 UTC by sixhobbits

2024-02-16 20:12 UTC, vcampitelli requested changes
Just some small typos

2024-02-16 20:12 UTC, vcampitelli commented on astro/src/content/docs/extend/examples/device-limiting.mdx
> +To make things a bit more concrete, let's use an example from the [quickStart guides](/docs/quickstarts/quickstart-javascript-express-web). The [ChangeBank](https://www.youtube.com/watch?v=CXDxNCzUsp
```suggestion
To make things a bit more concrete, let's use an example from the [quickstart guides](/docs/quickstarts/quickstart-javascript-express-web). The [ChangeBank](https://www.youtube.com/watch?v=CXDxNCzUspM) application is a simple banking application that allows users to convert dollars to coins.
```

2024-02-16 20:12 UTC, vcampitelli commented on astro/src/content/docs/extend/examples/device-limiting.mdx
> +If you are using Passport.js, you can include the `offline_access` scope in the `scope` key of the options object passed to the `authenticate` method. It should look something like the following.
```suggestion
If you are using [Passport.js](https://www.passportjs.org/), you can include the `offline_access` scope in the `scope` key of the options object passed to the `authenticate` method. It should look something like the following.
```

2024-02-16 20:12 UTC, vcampitelli commented on astro/src/content/docs/extend/examples/device-limiting.mdx
> +* The failed login message is the same generic message used for all webhook errors:** Adding other webhooks to your application will result in the same error message being displayed, regardless of th
```suggestion
* **The failed login message is the same generic message used for all webhook errors:** Adding other webhooks to your application will result in the same error message being displayed, regardless of the type of webhook failing. 
```

2024-02-16 20:12 UTC, vcampitelli commented on astro/src/content/docs/extend/examples/device-limiting.mdx
> +The web page posts the selected token Ids to the backend. You will need a route that accepts these token Ids and revokes the selected tokens using the DELETE method on the FusionAUth Refresh Token AP
```suggestion
The web page posts the selected token Ids to the backend. You will need a route that accepts these token Ids and revokes the selected tokens using the DELETE method on the FusionAuth Refresh Token API.
```

2024-02-16 20:12 UTC, vcampitelli commented on astro/src/content/docs/extend/examples/device-limiting.mdx
> +import {RemoteCode, RemoteValue} from '@fusionauth/astro-components';
```suggestion
import {RemoteCode} from '@fusionauth/astro-components';
```

2024-02-20 08:22 UTC, sixhobbits commented
@vcampitelli - sorry about those. Let me know if any other feedback.

2024-02-22 18:25 UTC, mooreds commented
@vcampitelli is this good to merge?

2024-02-22 19:34 UTC, vcampitelli approved these changes

2024-02-22 19:34 UTC, merged