update docs landing
FusionAuth/fusionauth-site pull request #2894
Opened 2024-02-15 18:14 UTC by alex-fusionauth

refers to https://github.com/FusionAuth/fusionauth-issues/issues/2570

2024-02-15 21:45 UTC, mooreds commented
@alex-fusionauth I think we weren't clear with the instructions, sorry. This doesn't match what I had in mind at all.

I created a couple of low fidelity mockups.

Here's where we add SDKs and APIs sections to the 'other resources' section. We should also add the 'reference' section here.

<img width="1834" alt="Screenshot 2024-02-15 at 2 26 30 PM" src="https://github.com/FusionAuth/fusionauth-site/assets/91825/a8335199-70e7-4844-82a1-307c0798466c">

Here's where we add a new section called 'documentation categories' which has all 5 documentation categories (though my mockup only shows four).

* get started
* lifecycle
* customize
* extend
* operate

<img width="1834" alt="Screenshot 2024-02-15 at 2 26 37 PM" src="https://github.com/FusionAuth/fusionauth-site/assets/91825/7a346225-c0b7-4f5d-805f-3ed5f8c75051">

The mockups have the headings, but not the text. I can provide the descriptive text for each section. The links should take you to the same place that the headings in the nav dropdown do.

Please let me know if this makes sense or if we should do a quick sync chat.

2024-02-16 00:02 UTC, mooreds requested changes
See comment about sections.

2024-02-27 17:41 UTC, mooreds requested changes
Reviewed text, added suggestions.

2024-02-27 17:41 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"title": "Reference",
Looks like `Reference` is in this section twice.

2024-02-27 17:41 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"description": "An opinionated set of higher-level constructs designed to simplify the integration of FusionAuth authentication workflows into applications.",
```suggestion
		"description": "Learn how to integrate and manage FusionAuth using your favorite programming language. You can choose either our client libraries (a thin, low-level wrapper over our APIs) or our SDKs (an opinionated set of higher-level constructs designed to simplify the integration of FusionAuth authentication workflows into applications).",
```

2024-02-27 17:41 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"description": "A comprehensive set of RESTful APIs that enable you to seamlessly integrate login, registration, and advanced user management features into your application.",
```suggestion
		"description": "A comprehensive set of RESTful APIs that enable you to integrate login, registration, and advanced user management features into your application. You can also build your own workflows and completely manage your FusionAuth instance using these APIs.",
```

2024-02-27 17:41 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"description": "Overview of how to use our quick start guides, installation options and how to call our APIs.",
```suggestion
		"description": "How to install and run FusionAuth, as well as documentation about core concepts such as tenants, users and applications.",
```

2024-02-27 17:41 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"description": "The FusionAuth lifecycle encompasses various stages and processes involved in managing user identities and access within the FusionAuth system",
```suggestion
		"description": "Covers registration/sign up, login/sign in, user management and migration.",
```

2024-02-27 17:41 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"description": "FusionAuth provides extensive customization options for enhancing the user experience and integrating your application seamlessly",
```suggestion
		"description": "How to customize the look and feel of pages and emails your users will see when they are logging in or registering.",
```

2024-02-27 17:41 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"description": "FusionAuth provides a mechanism to extend its functionality through plugins. This extension capability is designed to enhance the system's performance by loading plugins at startup
```suggestion
		"description": "Covers how to extend FusionAuth, including run time modifications of tokens, webhooks and events, and example applications.",
```

2024-02-27 17:41 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"description": "A collection of documentation and resources aimed at helping users manage, secure, and monitor their FusionAuth installation effectively.",
```suggestion
		"description": "How to operate FusionAuth, including advanced deployment configurations, Terraform and configuration management options, troubleshooting, and security and monitoring information.",
```

2024-03-05 22:23 UTC, mooreds requested changes

2024-03-05 22:23 UTC, mooreds commented on astro/public/img/icons/ruby.svg
do we need this any more?

2024-03-05 22:23 UTC, mooreds commented on astro/public/img/icons/typescript.svg
do we need this?

2024-03-05 22:23 UTC, mooreds commented on astro/src/pages/docs/index.astro
> +		"description": "An opinionated set of higher-level constructs designed to simplify the integration of FusionAuth authentication workflows into applications.",
Did you mean to resolve this and ignore my text suggestion?

2024-03-05 22:23 UTC, mooreds commented on astro/public/img/icons/openapi.svg
do we need this?

2024-03-05 22:23 UTC, mooreds commented on astro/public/img/icons/java.svg
do we need this?

2024-03-05 22:23 UTC, mooreds commented on astro/public/img/icons/dart.svg
do we need this?

2024-03-05 22:54 UTC, alex-fusionauth reviewed
updated on last review

2024-03-05 22:56 UTC, mooreds approved these changes

2024-03-05 23:16 UTC, merged