Updates to How SSO Works article
FusionAuth/fusionauth-site pull request #3093
Opened 2024-05-23 19:39 UTC by bradmccarty

2024-05-24 14:50 UTC, emilyjans approved these changes

2024-05-29 21:30 UTC, mark-robustelli requested changes
A few typos and one or two comments.

2024-05-29 21:30 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +Think of an SSO token as a digital key that contains user-identifying information, such as a username or email address. When a user logs in through an SSO service, this token is created and stored ei
```suggestion
Think of an SSO token as data that contains user-identifying information, such as a username or email address. When a user logs in through an SSO service, this token is created and stored either in the user's browser or within the SSO service's servers.
```

2024-05-29 21:30 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +The token is then passed between systems during the SSO process to verify the user's identity. This means that once a user is authenticated, they can seamlessly access other connected applications wi
```suggestion
The token is then passed between systems during the SSO process to verify the user's identity. This means that once a user is authenticated, they can seamlessly access other connected applications without having to log in again. The token is typically  digitally signed to ensure it comes from a trusted source, adding an extra layer of security to the authentication process.
```

2024-05-29 21:30 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +SSO reduces the risk of password-related security breaches by eliminating the need for users to remember and manage multiple credentials across different applications. It centralizes authentication,
```suggestion
SSO reduces the risk of password-related security breaches by eliminating the need for users to remember and manage multiple credentials across different applications. It centralizes authentication, making phishing attacks less effective and minimizing the overall attack surface for cybercriminals.
```

2024-05-29 21:30 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +SSO solutions provide your team with better visibility and control over user access. Admins can manage user accounts, permissions, and access controls, making it easier to provision and remove users
```suggestion
SSO solutions provide your team with better visibility and control over user access. Admins can manage user accounts, permissions, and access controls, from a single source making it easier to provision and remove users across multiple systems.
```

2024-05-29 21:30 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +Most SSO solutions all for [MFA](/articles/authentication/multi-factor-authentication) as an extra layer of security. So even if a password is compromised, the bad actor still needs a second form of
```suggestion
Most SSO solutions offer [MFA](/articles/authentication/multi-factor-authentication) as an extra layer of security. So even if a password is compromised, the bad actor still needs a second form of verification.
```
I assume this is what you meant.

2024-05-29 21:30 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +Centralized authentication and access controls in SSO help organizations meet regulatory requirements. When data access, user authentication, and audit trails become table stakes, then HIPAA, SOC2, a
"When data access....become table stakes....".  I think this needs to be reworded as those are always "table stakes" in my mind and should be for anyone.  This kind makes it seem like there are some cases where FusionAuth doesn't care about that. IMHO

2024-05-29 21:30 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +Absolutely! As long as you know what you're doing. SSO can be highly secure, but it depends on how it's implemented and managed. Let's break it down:
```suggestion
Absolutely! SSO can be highly secure, but it needs to be implemented and managed correctly. Let's break it down:
```

2024-05-29 21:30 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +SSO reduces the number of attack surfaces because users only login once, and with only a single set of credentials.
I have always had concerns that it goes the other way too.  If they get a hold of one, then they have all. :( but the idea is there.  When talking about security, you may say something like users can be disabled or removed in one central source for all applications.  No forgetting to remove them from a rarely used app.

2024-05-30 22:16 UTC, mark-robustelli approved these changes
@bradmccarty , one small typo and you are good to send it.

2024-05-30 22:16 UTC, mark-robustelli commented on astro/src/content/articles/authentication/how-sso-works.mdx
> +Centralized authentication and access controls in SSO help organizations meet regulatory requirements. Data access, user authentication, and audit trails are table stakes for FusionAuth. This makes H
```suggestion
Centralized authentication and access controls in SSO help organizations meet regulatory requirements. Data access, user authentication, and audit trails are table stakes for FusionAuth. This makes HIPAA, SOC2, and other standards easier to manage.
```

2024-05-30 22:34 UTC, merged