Update monitoring overview
FusionAuth/fusionauth-site pull request #3170
Opened 2024-07-31 14:00 UTC by sixhobbits

2024-08-06 16:33 UTC, alex-fusionauth requested changes
Update Vale `.github/vale/styles/config/vocabularies/FusionAuth/accept.txt`
Grafana
Alertmanager

Is there a better A11y version of the table?

2024-08-06 16:33 UTC, alex-fusionauth commented on astro/src/content/docs/operate/secure-and-monitor/opentelemetry.mdx
> +You can use Java system properties, environment variables, or edit the `fusionauth.properties` config file. See the [configuration reference](/docs/reference/configuration) for more info. For this ex
```suggestion
You can use Java system properties, environment variables, or edit the `fusionauth.properties` configuration file. See the [configuration reference](/docs/reference/configuration) for more info. For this example, environment variables will be used.
```

2024-08-07 09:23 UTC, sixhobbits commented
> Is there a better A11y version of the table?

@alex-fusionauth -  just to clarify, you mean not using the emoji ✅ etc for the feature comparison?

2024-08-07 12:56 UTC, alex-fusionauth commented
> 
> > Is there a better A11y version of the table?
> 
> @alex-fusionauth -  just to clarify, you mean not using the emoji ✅ etc for the feature comparison? 

Yeah exactly

2024-08-07 20:11 UTC, sixhobbits commented
> > > Is there a better A11y version of the table?
> > 
> > 
> > @alex-fusionauth -  just to clarify, you mean not using the emoji ✅ etc for the feature comparison?
> 
> Yeah exactly

we could change replace icons for "yes" and "no"?  But I'm not sure it would make that much difference as I think a screen reader would just read out "checkmark" and "restricted symbol" otherwise, and it would make it a bit harder to get a quick overview for people who don't need screenreaders. Or did you have something specific in mind?

2024-08-07 20:23 UTC, alex-fusionauth commented
> > > > Is there a better A11y version of the table?
> > > 
> > > 
> > > @alex-fusionauth -  just to clarify, you mean not using the emoji ✅ etc for the feature comparison?
> > 
> > 
> > Yeah exactly
> 
> we could change replace icons for "yes" and "no"? But I'm not sure it would make that much difference as I think a screen reader would just read out "checkmark" and "restricted symbol" otherwise, and it would make it a bit harder to get a quick overview for people who don't need screenreaders. Or did you have something specific in mind?

@sixhobbits we have this table that has "Yes" "No" and "-" for not relevant. I am thinking we should align with this. Even though I like the emoji style better ;)

https://fusionauth.io/docs/lifecycle/authenticate-users/oauth/endpoints#client-secret

2024-08-08 12:58 UTC, alex-fusionauth commented
@sixhobbits I think we are probably hitting our own updates here but can you merge main again?

2024-08-09 14:43 UTC, alex-fusionauth commented
@sixhobbits conflicts 🙏

2024-08-13 15:12 UTC, alex-fusionauth commented
@sixhobbits conflicts 🙏

2024-08-13 20:37 UTC, alex-fusionauth approved these changes

2024-08-13 20:38 UTC, merged