update references to editions and turn change them to refer to plans
FusionAuth/fusionauth-site pull request #3314
Opened 2024-10-01 21:16 UTC by mooreds

We made this change in our marketing long ago, but it never got pushed through our docs and blog.

2024-10-02 17:38 UTC, mark-robustelli requested changes
Overall looks good.  A few comments.  Most are around how we use "Community plan" vs "Community Plan".  I saw the same thing came up with Enterprise [Pp]lan.

2024-10-02 17:38 UTC, mark-robustelli commented on astro/src/content/docs/get-started/run-in-the-cloud/cloud.mdx
> +If these solutions do not meet your needs and you have an Enterprise plan, open a [support ticket](https://account.fusionauth.io/account/support/) to discuss options for regular data exports.
Is this Enterprise plan or Enterprise Plan?

2024-10-02 17:38 UTC, mark-robustelli commented on astro/src/content/docs/operate/roadmap/roadmap.mdx
> +If you'd like to pay us to build a feature, please [contact us](/contact) and ask about professional services. Please note that such a contract usually requires an Enterprise plan with a contract.
need to make consistent with [Name] [Pp]lan. Across changes.

2024-10-02 22:57 UTC, mooreds commented on astro/src/content/blog/announcing-fusionauth-1-52.mdx
> +description: This update brings passkeys to the free Community Plan of FusionAuth, enhancing security for everyone.
Thanks, we should standardize.

2024-10-02 23:00 UTC, mooreds commented on astro/src/content/blog/fusionauth-funding.mdx
> +What sets FusionAuth apart is our [free community option](/download/?utm_source=blog&utm_medium=blog+post&utm_campaign=funding-announcement), which has been downloaded over 13 million times. This pla
Yeah, I thought linking to the download page and calling it a plan was a bit weird, but maybe I'm wrong.

2024-10-04 20:06 UTC, mooreds commented on astro/src/content/blog/announcing-fusionauth-1-52.mdx
> +description: This update brings passkeys to the free Community Plan of FusionAuth, enhancing security for everyone.
I standardized on lower case P, upper case plan name. So like 'Enterprise plan'. This seemed to be the most common.

2024-10-04 21:58 UTC, mark-robustelli approved these changes
LGTM

2024-10-04 22:10 UTC, lyleschemmerling approved these changes

2024-10-04 22:12 UTC, merged