CTA for free trials
FusionAuth/fusionauth-site pull request #3392
Opened 2024-11-19 21:40 UTC by lyleschemmerling

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/7141152c-0978-4147-8bdd-bf2e773c4293">

2024-11-25 20:13 UTC, dcharles8 requested changes
Left a comment regarding the URL. Besides that, click testing all looked good to me.

2024-11-26 16:49 UTC, dcharles8 commented on astro/src/components/cta/FreeTrialCTA.astro
> +  <a href="https://account-local.fusionauth.io/account/free-trial/start?source=site" class="text-center w-full bg-orange-400 rounded px-4 py-2.5 text-sm font-bold uppercase">Start Free Trial</a>
Updated

2024-11-26 16:51 UTC, dcharles8 approved these changes

2024-11-27 18:36 UTC, bhalsey requested changes
CTA text isn't readable in light mode

2024-12-03 19:25 UTC, lyleschemmerling commented
<img width="701" alt="image" src="https://github.com/user-attachments/assets/81c1a64f-85fa-4a8a-a254-3994f3663c0f">

2024-12-03 19:33 UTC, bhalsey approved these changes

2024-12-03 20:10 UTC, merged