docs: add guide on how to build a multi-application dashboard/portal
FusionAuth/fusionauth-site pull request #3398
Opened 2024-11-21 13:04 UTC by sixhobbits

2025-01-22 20:47 UTC, bradmccarty submitted a review, later dismissed
This will be good after that one edit which also fixes the Vale error.

2025-01-22 20:47 UTC, bradmccarty commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +This guide will demonstrate a simpler and safer way to authenticate users from a central dashboard by making each application link in the dashboard point to the application's login page. From that po
```suggestion
This guide will demonstrate a simpler and safer way to authenticate users from a central dashboard by making each application link in the dashboard point to the application's login page. From that point onward, authentication follows the standard OAuth Authorization Code Flow.
```

2025-02-12 21:29 UTC, mooreds requested changes

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +In the language of authentication, FusionAuth is an identity provider (IdP) and your applications and websites are the service providers (SPs). One way to authenticate a user from a central dashboard
```suggestion
In the language of authentication, FusionAuth is an identity provider (IdP) and your applications and websites are the service providers (SPs). One way to authenticate a user from a central dashboard is to use an IdP-initiated login. In other words, the dashboard will log the user in, and then redirect them to the selected app. In short, a service provider application will receive a login that it didn't initiate itself. This has security implications.
```

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +This guide will demonstrate a simpler and safer way to authenticate users from a central dashboard by making each application link in the dashboard point to the application's login page. From that po
```suggestion
This guide will demonstrate a simpler and safer way to authenticate users from a central dashboard by making each application link in the dashboard point to the application's login page. From that point onward, authentication follows the standard OAuth Authorization Code grant.
```

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +The next section of this guide will show you how to make a dashboard for two existing FusionAuth applications in the same tenant. All this requires is customizing the theme for the index landing page
```suggestion
The next section of this guide will show you how to make a dashboard for two existing FusionAuth applications in the same tenant. All this requires is customizing the theme for the index landing page of the FusionAuth site. The guide will first show you how to install FusionAuth and make two simple web applications. If you already have a FusionAuth installation with existing applications, you can skip ahead to [the section that creates the dashboard](#make-a-dashboard).
```

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Use `git clone` to clone the repository at https://github.com/fusionauth/fusionauth-example-multiapp-dashboard, or download and unzip it.
This repo doesn't exist?

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Use `git clone` to clone the repository at https://github.com/fusionauth/fusionauth-example-multiapp-dashboard, or download and unzip it.
When it does get moved over, we should add it to exampleapps.json as well.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +  ```sh
We don't need spaces prepended, do we?

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +  ```sh
Same comment about spacing in front of the triple backticks.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +  docker run --platform=linux/amd64 --rm -v ".:/app" -w "/app" node:23-alpine3.19 sh -c  "npm install"
This won't work on an ARM based chip, I'm guessing. What have you done in the past? can you create a docker compose file for these applications that is cross platform?

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +The Changebank app is available at http://localhost:3000.
```suggestion
The Changebank app is now running at http://localhost:3000. 
```

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +To learn how to make a simple Node.js app that uses FusionAuth, read the [quickstart](/docs/quickstarts/quickstart-javascript-express-web).
```suggestion
```

Let's not distract the user with a link to the quickstart.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +  ```sh
Same thing with the spaces in front of the backticks.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +  ```sh
Same thing with the spaces in front of the backticks.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +  docker run --platform=linux/amd64 --rm -v ".:/app" -w "/app" node:23-alpine3.19 sh -c  "npm install"
Same comments about docker run.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Before making the dashboard, check that you can log in to all three applications. Either use an incognito browser window or don't enable [Keep me signed in](/docs/lifecycle/authenticate-users/logout-
```suggestion
Before making the dashboard, check that you can log in to all three applications. Either use an incognito browser window or don't enable <InlineUIElement>[Keep me signed in](/docs/lifecycle/authenticate-users/logout-session-management#fusionauth-sso)</InlineUIElement> when logging in, otherwise, you won't see the login form in the rest of this guide:
```

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +If you enabled <InlineUIElement>Keep me signed in</InlineUIElement>, logging out of an application won't log you out of FusionAuth. It will only delete the session of the application. Next time you t
```suggestion
If you enabled <InlineUIElement>Keep me signed in</InlineUIElement>, logging out of an application won't necessarily log you out of FusionAuth. It will only delete the session of the application. Next time you try to log in, FusionAuth will see the FusionAuth authentication cookie in your browser and automatically log you in.
```

It will if the application redirects to FusionAuths `/oauth2/logout` URL.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Look at the current FusionAuth landing page at http://localhost:9011.
```suggestion
Now that you have applications up and running, let's build the dashboard.

Look at the current FusionAuth landing page at http://localhost:9011. 
```

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Log in to your [FusionAuth web interface](http://localhost:9011/admin) and browse to <Breadcrumb>Customizations -> Themes</Breadcrumb>.
thank you for using `<Breadcrumb>`!

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Notice there are three themes in the list. The first two are the default FusionAuth themes. The last one, <InlineUIElement>Bank theme</InlineUIElement>, was added by `kickstart.json` when you ran Doc
```suggestion
Notice there are three themes in the list. The first two are the default FusionAuth themes. The last one, <InlineUIElement>Bank theme</InlineUIElement>, was added by Kickstart when you started FusionAuth up. Read about Kickstart [here](/docs/get-started/download-and-install/development/kickstart).
```

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +  ```html
This should be remote code pulled from a github repo, not inline FTL.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +docker rmi postgres:16.0-bookworm fusionauth/fusionauth-app:1.51.2 node:23-alpine3.19
I don't think we need to delete the images.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Besides a little CSS for styling, the code above has only two changes: Adding hyperlink `<a href="http://localhost:3000/account">Changebank</a>` elements for the two applications. Note that the links
```suggestion
Besides a little CSS for styling, the code above only adds links for the two applications. The links don't point to the login page of the target application. Instead, they point to the logged-in main page. If the user isn't logged in to FusionAuth, they will be automatically redirected to the app's login page. If they are already logged in, they will be taken straight to the app. This saves the user time while still protecting the application content.
```

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Besides a little CSS for styling, the code above has only two changes: Adding hyperlink `<a href="http://localhost:3000/account">Changebank</a>` elements for the two applications. Note that the links
Please also remote code include `bankApp/routes/index.js` and show how it works, rather than asking the user to look at it.

2025-02-12 21:29 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +
```suggestion

You can extend this to any number of applications, just like Google does.

### Partial Access

You can require application registration for users befeore access is allowed. Do so by enabling the <InlineUIElement>require registration</InlineUIElement> setting in the <Breadcrumb>OAuth</Breadcrumb> tab of the application. 

When this is configured, a user who is not registered to the Changeinsurance application will not be able to access it, even though they can click on the link. They simply won't be logged in.

```

Make sure that the kickstart does set the `require registration` setting for each application.

2025-02-13 10:52 UTC, sixhobbits commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +  docker run --platform=linux/amd64 --rm -v ".:/app" -w "/app" node:23-alpine3.19 sh -c  "npm install"
it should usually 'just work' through emulation I think (we've tested this on x64 and M1 machines), but yes in general we struggle a bit with figuring out how to do this nicely as we often see little niggles on different platforms with Docker. 

That image is available on all platforms, so maybe we should just add a note at this point advising the reader to match their platform if they have issues?

2025-02-14 13:09 UTC, sixhobbits commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Use `git clone` to clone the repository at https://github.com/fusionauth/fusionauth-example-multiapp-dashboard, or download and unzip it.
This is the repo https://github.com/ritza-co/fusionauth-example-multiapp-dashboard

We have added it to exampleapps, assuming you keep the same name when moving it to your org

2025-02-19 21:46 UTC, mooreds commented on astro/src/content/docs/extend/examples/multi-application-dashboard.mdx
> +Use `git clone` to clone the repository at https://github.com/fusionauth/fusionauth-example-multiapp-dashboard, or download and unzip it.
sounds good.This is there now: https://github.com/FusionAuth/fusionauth-example-multiapp-dashboard

2025-02-19 22:01 UTC, mooreds approved these changes

2025-02-19 22:02 UTC, merged