Add entity api doc
FusionAuth/fusionauth-site pull request #543
Opened 2021-04-07 22:39 UTC by mooreds

This is the entity api doc.

A couple of issues:

* what is email in this context? https://github.com/FusionAuth/fusionauth-api/blob/master/src/main/java/io/fusionauth/api/service/search/DatabaseEntitySearchEngine.java#L59

2021-05-04 17:03 UTC, bguyza requested changes
First pass complete.  Nice job!

There is a lot going on in this PR so I'll be happy to do another pass once you've had a chance to address comments here.  I tried to be as exhaustive as possible.  Let me know if you have any questions.

2021-05-04 17:03 UTC, bguyza commented on site/docs/v1/tech/apis/_entity-grant-response-body-base.adoc
> +
```suggestion

[field]#{base_field_name}.entity# [type]#[Entity]#::
The entity to which access is granted.
```

2021-05-04 21:08 UTC, mooreds commented on site/docs/src/json/entities/response.json
> +      "id": "092dbded-30af-4149-9c61-b578f2c72f57",
It looks like the current FusionAuth behavior is to only respond with the id, so let's follow that.

2021-05-04 21:12 UTC, mooreds commented on site/docs/src/json/entities/response.json
> +      "id": "092dbded-30af-4149-9c61-b578f2c72f57",
Actually, I'm wrong, it does include the type info. will add that.

2021-05-04 21:17 UTC, mooreds commented on site/docs/v1/tech/apis/_entity-response-body-base.adoc
> +
So it looks like parent ids are in the schema but don't have any supporting code yet, so I'll remove it.

2021-05-05 03:02 UTC, mooreds commented
So I ended up breaking out grants and moving all the apis down under `entity management`. 

Incorporated all your suggestions and wrote scripts against the api.

2021-05-05 20:27 UTC, bguyza approved these changes
This LGTM.  I really like how you reorganized the content as well.

2021-05-05 21:23 UTC, merged