Update External JWT Provider Doc
FusionAuth/fusionauth-site pull request #551
Opened 2021-04-08 22:29 UTC by jobannon

# Summary 
- Minor changes to documentation and spelling.
- Update lanaguage around managed domains.  A managed domain is not a requirement.

2021-04-08 23:30 UTC, mooreds requested changes
A few small changes, other than that looks good.

2021-04-08 23:30 UTC, mooreds commented on site/docs/v1/tech/identity-providers/external-jwt/index.adoc
> +If you will not have JWTs that do not contain the `kid` or another key identifier, you will not use this feature. When this toggle is enabled, the `Key identifier` field will be disabled and no longe
I think this means:

"If you only have JWTs with the `kid` claim, or another key identifier, you will not use this feature. When this toggle is enabled, the [field]#Key identifier# field will be disabled and no longer required."

2021-04-08 23:30 UTC, mooreds commented on site/docs/v1/tech/identity-providers/external-jwt/index.adoc
>  {empty} +
This leaves weird empty space. Can we get rid of it?

2021-04-08 23:30 UTC, mooreds commented on site/docs/v1/tech/identity-providers/external-jwt/index.adoc
> +====
All the other notes I've seen look like

```
[NOTE]
====
Note contents
====
```

Please maintain that pattern.

2021-04-08 23:30 UTC, mooreds commented on site/docs/v1/tech/identity-providers/external-jwt/index.adoc
> +To configure a lambda, navigate to [breadcrumb]#Customizations -> Lambdas#.
Great catch!

2021-04-08 23:30 UTC, mooreds commented on site/docs/v1/tech/identity-providers/external-jwt/index.adoc
> +For example, if a user's email address is `jared@piedpiper.com`, in order for a JWT owned by Jared to be reconciled to FusionAuth using this identity provider, `piedpiper.com` could be configured as
Can you add to the end: "You may leave this blank. If you do so, then any email can be used with this identity provider. This is helpful if you are not certain which email domains your users will have."

2021-04-15 14:31 UTC, mooreds commented
@jobannon how is this going?

2021-04-22 22:20 UTC, mooreds commented
@jobannon ping!

2021-04-23 14:59 UTC, jobannon commented
@mooreds  pong! 😉

2021-04-23 14:59 UTC, merged