Update Login response codes for gated content
FusionAuth/fusionauth-site pull request #679
Opened 2021-05-17 21:33 UTC by bguyza

This PR updates response codes to include `213` for any login API.  Specifically:
- /api/login: `login-response-codes.adoc`
- /api/two-factor/login: `login-response-codes.adoc`
- /api/identity-provider/login: `_identity-provider-login-response-body.adoc`
- /api/passwordless/login: `login-response-codes.adoc`

2021-05-18 23:16 UTC, mooreds requested changes

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/registrations.adoc
> +Using [field]#verificaitonId# in the URL segment is deprecated as of version 1.27.0 and may be removed in the future. This API now takes this field in the request body.
```suggestion
Using [field]#verificaitionId# in the URL segment is deprecated as of version 1.27.0 and may be removed in the future. This API now takes this field in the request body.
```

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/users.adoc
> +Using [field]#verificaitonId# in the URL segment is deprecated as of version 1.27.0 and may be removed in the future. This API now takes this field in the request body.
```suggestion
Using [field]#verificationId# in the URL segment is deprecated as of version 1.27.0 and may be removed in the future. This API now takes this field in the request body.
```

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/users.adoc
> +Using [field]#verificaitonId# in the URL segment is deprecated as of version 1.27.0 and may be removed in the future. This API now takes this field in the request body.
You need to add a Request Body section now, correct?

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/registrations.adoc
> +Using [field]#verificaitonId# in the URL segment is deprecated as of version 1.27.0 and may be removed in the future. This API now takes this field in the request body.
You need to add a Request Body section now, correct?

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/_login-response-codes.adoc
> +|The user's email address has not yet been verified. The response will contain the User object that was authenticated. If the verification strategy has been set to `Form Field`, the response will con
Is it worth adding a sample response, like the 242 and 203 responses have?

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/_login-response-codes.adoc
> +|The user's registration has not yet been verified. The response will contain the User object that was authenticated. If the verification strategy has been set to `Form Field`, the response will cont
Is it worth adding a sample response, like the 242 and 203 responses have?

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/identity-providers/_identity-provider-login-response-body.adoc
> +|The user's email address has not yet been verified. The response will contain the User object that was authenticated. If the verification strategy has been set to `Form Field`, the response will con
Is it worth adding a sample response, like the 242 and 203 responses have?

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/identity-providers/_identity-provider-login-response-body.adoc
> +|213
Is it worth adding a sample response, like the 242 and 203 responses have?

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/login.adoc
> +|The user's email address has not yet been verified. The response will contain the User object that was authenticated. If the verification strategy has been set to `Form Field`, the response will con
Is it worth adding a sample response, like the 242 and 203 responses have?

2021-05-18 23:16 UTC, mooreds commented on site/docs/v1/tech/apis/login.adoc
> +|The user's registration has not yet been verified. The response will contain the User object that was authenticated. If the verification strategy has been set to `Form Field`, the response will cont
Is it worth adding a sample response, like the 242 and 203 responses have?

2021-05-19 17:03 UTC, bguyza commented
@mooreds
- Updated fields to include a request body. It actually includes a oneTimeCode field too so I'm glad you called that out.
- I was going back and forth with regards to adding sample responses for 212 and 213.  The reason I decided to omit them was because the response contains the entire User object with the emailVerificationId or registrationVerificationId added to the json and it takes up a lot of real-estate on the page.  Since the existing 212 didn't have an example with the User object I thought the addition of one more field didn't necessarily warrant adding large example responses.

If you think its best to include it, I can go ahead and add.  Thoughts?

2021-05-19 17:06 UTC, mooreds commented
@bguyza makes sense to not include the body in that case.

2021-05-19 17:52 UTC, merged