Deactivating, reactivating, and deleting a FusionAuth user in Python
FusionAuth/fusionauth-site pull request #837
Opened 2021-07-23 22:51 UTC by matt1hathcock

- Updated date added
- Updated site navigation
- Updated title and section headers
- Updated table of contents
- Updated Python version
- Removed Ubuntu reference
- Updated images with class="img-fluid"
- ID -> Id
- 127.0.0.1 -> localhost, and removed hyperlink
- bash -> zsh
- shell prompts removed
- added hyperlink to "creating-an-api-key"
- "FusionAuth Python client library" where referenced
- other changes

2021-08-19 21:00 UTC, mooreds requested changes
A few changes.

Meta comments:

* Did you run this through google docs for a grammar check?
* David is going to create a new header image, will share when that is done
* what version of fusionauth did you use for the update? Please add a call out like you did for the other tutorial
* is python-first-app the correct kickstart file? Wasn't sure if there was another one.

2021-08-19 21:00 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
```suggestion
When a user is locked, they can no longer log in to any applications, but they are not removed from the system. This is useful if you want to re-enable them later (perhaps after they've paid their bill).

```

2021-08-19 21:00 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +```zsh
Isn't this python?

2021-08-19 21:00 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +For our next trick, we will be deleting a test user from the server. If you filled out a lot of profile information on your regular test user, you might want to create an empty test user for this tut
Why would you delete a user vs deactivate them? Did that get covered above (might have missed it).

2021-08-19 21:00 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
>  client = FusionAuthClient('YOUR-API', 'http://localhost:9011')
```suggestion
client = FusionAuthClient('YOUR-API-KEY', 'http://localhost:9011')
```

2021-08-19 21:00 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +If successful, you will get a response of `None` and the user will now be deleted from FusionAuth. You can test this again by refreshing the "Users" page in your browser.
Hmmm. Is this a hard delete or a soft delete? (Hard delete actually removes them from the system, soft delete lets you restore later.)  Looking at the source, it looks like a hard delete: https://github.com/FusionAuth/fusionauth-python-client/blob/master/src/main/python/fusionauth/fusionauth_client.py

2021-08-19 21:00 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +1. How to deactivate a user
Did you add any sections? I think so (kickstart)

2021-08-19 21:00 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +## Setting up FusionAuth using a Kickstart file
I'd add a section here defining each of these terms. Something like this (but jazz it up if you want).

* deactivate, also known as a soft delete or account locking, lets you disable the ability for a user to login temporarily
* reactivate removes the lock and lets a user login
* delete, also known as a hard delete, removes all data for a user and can't be undone. Beware!

2021-08-19 21:00 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +Didn't find your error here? Visit [https://fusionauth.i/docs/v1/tech/apis/users](/docs/v1/tech/apis/users) for more response codes, or visit [https://fusionauth.io/docs/v1/tech/troubleshooting](/doc
```suggestion
Didn't find your error here? Visit [https://fusionauth.i/docs/v1/tech/apis/users](/docs/v1/tech/apis/users) for more response codes, or visit [https://fusionauth.io/docs/v1/tech/troubleshooting](/docs/v1/tech/troubleshooting) for more troubleshooting suggestions. You can also ask a question on the [FusionAuth Forum](https://fusionauth.io/community/forum/). As always, if you have a support contract feel free to [contact FusionAuth support](https://account.fusionauth.io/account/support).
```

2021-08-19 21:29 UTC, mooreds commented on site/_layouts/blog-post.liquid
> +            <div class="author-date">{{ page.author }}&nbsp;&nbsp;|&nbsp;&nbsp;{{ page.date | date_to_string: "ordinal", "US" }}{%if page.updated_date%}&nbsp;&nbsp;|&nbsp;&nbsp;Most recently updated:
This was me, fyi.

2021-09-14 22:20 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +## Setting up FusionAuth using a Kickstart file
looks good now.

2021-09-14 22:21 UTC, mooreds commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +```zsh
please change it to python.

2021-09-14 22:22 UTC, mooreds commented
One change and then merge away! https://github.com/FusionAuth/fusionauth-site/pull/837/files#r708694133

2021-09-16 19:15 UTC, matt1hathcock commented on site/_posts/2019-10-08-deactivating-reactivating-deleting-user-fusionauth-python.md
> +```zsh
fixed in latest commit

2021-09-16 22:10 UTC, merged