Add Registration Gate Tutorial
FusionAuth/fusionauth-site pull request #893
Opened 2021-08-21 00:01 UTC by jobannon

### Summary  - DRAFT
There seems to be some confusion on how these two gating flows work (registration and email verification).  
Add a second explainer tutorial.

Closes https://github.com/FusionAuth/fusionauth-site/issues/892

2021-09-09 17:47 UTC, mooreds requested changes
Overall pretty good.

* Please run through google docs or grammarly if you haven't (I thought I saw one typo).
* There's a lot of overlap, is there room for a single template that pulls in different pieces? Or is that overkill?
* I think it'd be useful to have the examples all be pied piper/hooli rather than google/youtube
* I think you do a good job of emphasizing that it is rare that folks what registration verification, but I added reasons why you might. That might be good.
* All we have in the API for `user.verified` is a very simple explanation. It'd be good to add in some of the details you outlined in this tutorial to that API doc (which probably will get a lot more eyes).

2021-11-02 04:28 UTC, jobannon commented
@mooreds This is ready for merge; I put notes in your initial comment.
@robotdan Let me know if you have any thoughts on this PR.  

Can merge this week if all is good.

2021-11-02 17:37 UTC, mooreds requested changes
full sentences and run through spell check.

the point of registration verification is that the user who is registered for an application explicitly verified their registration via clicking on a link. So the point is both parties know the user explicitly verified. This is in contrast to user verification, where the point is that the email address is really controlled by the person who signed up for the account. This was a bit confusing to me in the piedpiperchat/notahotdog example (which was otherwise great!).

Is all verification a paid feature or only gating? You mix the two a bit, so it might be worth calling it out. What does gating mean? The user must be verified before they are allowed to login (the JWT is never issued), correct? 

common questions are good but the titles are a bit loud. Maybe include the title in the question? I made those suggested edits.

General menu weirdness
- looks like guide is tagged
- user account lockout in two places
- need redirect if you are moving user account lockout to a different directory (and if it is under a menu, it should be moved to that directory).

Should merge master to this branch

2021-11-02 17:37 UTC, mooreds commented on site/_layouts/doc.liquid
> +                        <li {% if page.url == "/docs/v1/tech/tutorials/setting-up-user-account-lockout/" %}class="active"{% endif %}><a href="/docs/v1/tech/tutorials/setting-up-user-account-lockout/"
I think you need to remove this from the other section of the menu it is in.

2021-11-02 17:37 UTC, mooreds commented on site/_layouts/doc.liquid
> +                        <li {% if page.url == "/docs/v1/tech/tutorials/gate-accounts-until-user-email-verified/" %}class="active"{% endif %}><a href="/docs/v1/tech/tutorials/gating/gate-accounts-unti
the page.url links here don't include `gating`. Is that intentional?

2021-11-02 17:37 UTC, mooreds commented on site/docs/v1/tech/tutorials/gating/_common-questions-gating.adoc
> +**Question**: Will all my existing users get emails for either gate once enabled?
```suggestion
**Question**: Will all my existing users retroactively get emails for either gate once enabled?
```

2021-11-02 17:37 UTC, mooreds commented on site/docs/v1/tech/tutorials/gating/_common-questions-gating.adoc
> +=== What About Enabling Both Gates?
```suggestion
```

2021-11-02 17:37 UTC, mooreds commented on site/docs/v1/tech/tutorials/gating/_common-questions-gating.adoc
> +**Answer**: If you enable both registration verification and email verification, there will be a bit of redundancy (this is fine and expected). Consider the use case of ten applications and one commo
You don't answer the question directly here. 

Will the user get 2 emails for the 10th application? (I am guessing yes.)

2021-11-02 17:37 UTC, mooreds commented on site/docs/v1/tech/tutorials/gating/_troubleshooting-gating.adoc
> +If attempting to verify email, ensure you have selected the appropriate template (`email verification` as opposed to `registration verification` in this instance)
This sentence reads weird. Maybe "If attempting to verify email addresses..."

2021-11-02 17:37 UTC, mooreds commented on site/docs/v1/tech/tutorials/gating/_troubleshooting-gating.adoc
> +If attempting to verify email, ensure you have selected the appropriate template (`email verification` as opposed to `registration verification` in this instance)
Make sure the text matches case of the image: `Email Verification`, etc.

2021-11-02 17:37 UTC, mooreds commented on site/docs/v1/tech/tutorials/gating/_troubleshooting-gating.adoc
> +image::tutorials/email-verify-wrong.png[Incorrect Template Email Verification,width=1200]
I like the 'checkmark' and 'prohibited' stamps, but the prohibited one should be red.

2021-11-02 17:37 UTC, mooreds commented on site/docs/v1/tech/tutorials/gating/_troubleshooting-gating.adoc
> +image::tutorials/tenant-timeouts.png[Tenant Timeouts Screenshot,width=1200]
use red squares, not black arrows, to outline critical fields.

2021-11-02 17:37 UTC, mooreds commented on site/docs/v1/tech/tutorials/gating/registration-gate-accounts-until-verified.adoc
> +.User Object With Registration Verification Turned Off Initially JSON
This isn't really the user object at this point. It is the Registrations array, excerpted from the User object.

Please update the title of this JSON fragment.

2021-11-08 23:33 UTC, mooreds commented
@jobannon is this ready for re-review?

2021-11-09 22:56 UTC, merged